#!/bin/bash
#+----------------GERANDO LOG-----------------------+OK"
SCRIPT=`basename $0`
LOG=`echo /opt/zimbra/$SCRIPT.log | sed s/'.sh'/'.log'/g`
exec &> >(tee -a "$LOG")
echo "[`date`] ==== Inicio de rotina..."
#+----------------GERANDO LOG-----------------------+OK"

clear

#Checa se o usuario é root
LOCAL_USER=`id -u -n`

if [ $LOCAL_USER != "root" ] ; then
	echo "     Rodar como usuario root"
	echo "     saindo..."
	echo ""
	exit
fi
	dir="Diretorio Atual		 : `pwd`"
	hostname="Hostname			 : `hostname --fqdn`"
	ip="IP						 : `wget -qO - icanhazip.com`"
	#ip="IP						 : `ifconfig | awk 'NR>=2 && NR<=2' | awk '{print $3}'`"
    versaoso="Versao S.O.		 : `lsb_release -d | cut -d : -f 2- | sed 's/^[ \t]*//;s/[ \t]*$//'`"
	release="Release			 : `lsb_release -r | cut -d : -f 2- | sed 's/^[ \t]*//;s/[ \t]*$//'`"
	codename="Codename			 : `lsb_release -c | cut -d : -f 2- | sed 's/^[ \t]*//;s/[ \t]*$//'`"
	kernel="Kernel				 : `uname -r`"
	arquitetura="Arquitetura	 : `uname -m`"
	versaozimbra="Versao Zimbra : `su - zimbra -c 'zmcontrol -v'`"
    echo "+-------------------------------------------------+"
    echo "|           Utilitario para Zimbra  v1.15         |"
    echo "+-------------------------------------------------+"
    echo "+-------------------------------------------------+"
    echo "| Escrito por:                                    |"
    echo "| Thiago Castro - www.hostlp.cloud                |"
    echo "+-------------------------------------------------+"
    echo
    echo $dir
	echo "+-------------------------------------------------+"
	echo $hostname
	echo "+-------------------------------------------------+"
	echo $ip
	echo "+-------------------------------------------------+"
	echo $versaoso
	echo "+-------------------------------------------------+"
	echo $release
	echo "+-------------------------------------------------+"
	echo $codename
	echo "+-------------------------------------------------+"
    echo $kernel
	echo "+-------------------------------------------------+"
    echo $arquitetura
	echo "+-------------------------------------------------+"
	echo $versaozimbra
	echo "+-------------------------------------------------+"
	echo
	echo "Aperte <ENTER> para continuar e começar..."
	read 
	sleep 5
	echo
	echo "==================EXECUTANDO======================="
	echo
	
#Variavel
UsrZ="su - zimbra -c"

#Pega Informações do Servidor
#echo "Pegando Informações do Servidor"
#$UsrZ 'zmprov -l gs `zmhostname` | grep -i port'
#$UsrZ 'zmprov -l gs `zmhostname` | grep MailMode'
#$UsrZ 'zmprov -l gs `zmhostname` | grep -i installed'
#$UsrZ 'zmprov -l gacf | grep zimbraMailPurgeSleepInterval'
#	 echo "+-------------------------------------------------+OK"

#Define portas de Proxy para 0
echo "Definindo portas de Proxy para 0"
$UsrZ 'zmproxyctl stop' 1&> /dev/null
$UsrZ 'zmprov -l ms `zmhostname` zimbraImapProxyBindPort 0'
$UsrZ 'zmprov -l ms `zmhostname` zimbraImapSSLProxyBindPort 0'
$UsrZ 'zmprov -l ms `zmhostname` zimbraPop3ProxyBindPort 0'
$UsrZ 'zmprov -l ms `zmhostname` zimbraPop3SSLProxyBindPort 0'
$UsrZ 'zmprov -l ms `zmhostname` zimbraMailProxyPort 0'
$UsrZ 'zmprov -l ms `zmhostname` zimbraMailSSLProxyPort 0'
$UsrZ 'zmprov -l ms `zmhostname` zimbraAdminProxyPort 0'
$UsrZ 'zmprov -l mcf zimbraImapProxyBindPort 0'
$UsrZ 'zmprov -l mcf zimbraImapSSLProxyBindPort 0'
$UsrZ 'zmprov -l mcf zimbraPop3ProxyBindPort 0'
$UsrZ 'zmprov -l mcf zimbraPop3SSLProxyBindPort 0'
$UsrZ 'zmprov -l mcf zimbraMailProxyPort 0'
$UsrZ 'zmprov -l mcf zimbraMailSSLProxyPort 0'
$UsrZ 'zmprov -l mcf zimbraAdminProxyPort 0'
	 echo "+-------------------------------------------------+OK"

#Define as portas nao "Proxy" para as portas padrão desejada
echo "Definindo portas não Proxy para o padrão"
$UsrZ 'zmprov -l ms `zmhostname` zimbraImapBindPort 143'
$UsrZ 'zmprov -l ms `zmhostname` zimbraImapSSLBindPort 993'
$UsrZ 'zmprov -l ms `zmhostname` zimbraPop3BindPort 110'
$UsrZ 'zmprov -l ms `zmhostname` zimbraPop3SSLBindPort 995'
$UsrZ 'zmprov -l ms `zmhostname` zimbraMailPort 80'
$UsrZ 'zmprov -l ms `zmhostname` zimbraMailSSLPort 443'
$UsrZ 'zmprov -l ms `zmhostname` zimbraAdminPort 7071'
$UsrZ 'zmprov -l ms `zmhostname` zimbraMailMode redirect'
$UsrZ 'zmprov -l ms `zmhostname` zimbraReverseProxyMailMode both'
$UsrZ 'zmprov -l mcf zimbraImapBindPort 143'
$UsrZ 'zmprov -l mcf zimbraImapSSLBindPort 993'
$UsrZ 'zmprov -l mcf zimbraPop3BindPort 110'
$UsrZ 'zmprov -l mcf zimbraPop3SSLBindPort 995'
$UsrZ 'zmprov -l mcf zimbraMailPort 80'
$UsrZ 'zmprov -l mcf zimbraMailSSLPort 443'
$UsrZ 'zmprov -l mcf zimbraAdminPort 7071'
$UsrZ 'zmprov -l mcf zimbraMailMode redirect'
$UsrZ 'zmprov -l mcf zimbraReverseProxyMailMode both'
	 echo "+-------------------------------------------------+OK"

#Mudar porta de HTTP para HTTPS
echo "Definindo redirecionamento HTTP para HTTPS"
$UsrZ 'zmtlsctl redirect' 1&> /dev/null
	 echo "+-------------------------------------------------+OK"

#Acertando SSH port e SSL
echo "Acertando SSH port e chaves SSL"
SSHP1="`cat /etc/ssh/sshd_config |grep Port | cut -d' ' -f2`"
echo "Porta SSH Atual -> $SSHP1"
echo -n "Porta SSH Atual: "
read SSHP2
     echo "+-------------------------------------------------+OK"
$UsrZ 'zmprov -l ms `zmhostname` zimbraRemoteManagementPort '$SSHP2''
$UsrZ 'zmprov -l mcf zimbraRemoteManagementPort '$SSHP2''
$UsrZ 'cd /opt/zimbra/bin/'
$UsrZ '/opt/zimbra/bin/zmsshkeygen'
$UsrZ '/opt/zimbra/bin/zmupdateauthkeys'
     echo "+-------------------------------------------------+OK"
#https://wiki.zimbra.com/index.php?title=Mail_Queue_Monitoring

#Acertando o LMTA
echo "Acertando o LMTA"
$UsrZ 'zmprov -l ms `zmhostname` zimbraMtaLmtpHostLookup native'
$UsrZ 'zmprov -l mcf zimbraMtaLmtpHostLookup native'
	 echo "+-------------------------------------------------+OK"

#Configurando resposta rapida quando der Over Quota
echo "Configurando resposta rapida quando der Over Quota"
$UsrZ 'zmprov -l mcf zimbraLmtpPermanentFailureWhenOverQuota TRUE'
	 echo "+-------------------------------------------------+OK"

#Configurando tempo de vida em fila
echo "Configurando tempo de vida em fila"
$UsrZ 'zmprov -l mcf zimbraMtaBounceQueueLifetime 1d'
$UsrZ 'zmprov -l mcf zimbraMtaMaximalQueueLifetime 1d'
$UsrZ 'zmprov -l mcf zimbraMtaSmtpdSaslAuthenticatedHeader yes'
$UsrZ 'zmprov -l mcf zimbraMtaQueueRunDelay 300s'
$UsrZ 'zmprov -l mcf zimbraMtaMaximalBackoffTime 4000s'
$UsrZ 'zmprov -l mcf zimbraMtaMinimalBackoffTime 300s'
	 echo "+-------------------------------------------------+OK"
#http://www.bachus.us/blog/2014/07/02/securing-zimbra-smtp/

#Acertando os Atalhos
echo "Acertando os Atalhos"
rm -rf /sbin/postsuper /sbin/mailq /sbin/postqueue
ln -s /opt/zimbra/common/sbin/postsuper /sbin/postsuper
ln -s /opt/zimbra/common/sbin/mailq /sbin/mailq
ln -s /opt/zimbra/common/sbin/postqueue /sbin/postqueue
echo postsuper -d ALL > /sbin/del-mail ; chmod +x /sbin/del-mail
echo tail -f /var/log/mail.log > /sbin/maillog ; chmod +x /sbin/maillog
	 echo "+-------------------------------------------------+OK"

#Aumentando o limite do tamanho de anexos
echo "Aumentando o limite do tamanhoa de anexos -> 10mb = 10485760 / 20mb = 20971520 / 30mb = 31457280 / 40mb = 41943040 / 50mb = 52428800"
echo -n "Limitar anexos em...: "
read LANX
$UsrZ 'zmprov -l mcf zimbraMailContentMaxSize '$LANX''
$UsrZ 'zmprov -l mcf zimbraImapMaxRequestSize '$LANX''
$UsrZ 'zmprov -l mcf zimbraMtaMaxMessageSize '$LANX''
$UsrZ 'zmprov -l mcf zimbraFileUploadMaxSize '$LANX''
$UsrZ 'zmprov -l mcf zimbraFileUploadMaxSizePerFile '$LANX''
	 echo "+-------------------------------------------------+OK"

#Acertando os banners
echo "Acertando os banners"
$UsrZ 'zmlocalconfig -e postfix_smtpd_banner="`hostname --fqdn`"'
$UsrZ 'zmprov -l mcf zimbraMtaMyHostname `hostname --fqdn`'
	 echo "+-------------------------------------------------+OK"

#Alterando logos de todos os dominios
echo "Alterando logos de todos os dominios"
$UsrZ 'for dominios in $(zmprov -l gad); do zmprov -l md $dominios zimbraSkinLogoURL https://site.hostlp.com.br; done'
$UsrZ 'for dominios in $(zmprov -l gad); do zmprov -l md $dominios zimbraSkinLogoLoginBanner https://site.hostlp.com.br/imagens/zimbra/Logotipo_Novo_130x58.png; done'
$UsrZ 'for dominios in $(zmprov -l gad); do zmprov -l md $dominios zimbraSkinLogoAppBanner https://site.hostlp.com.br/imagens/zimbra/Logotipo_Novo_80x36.png; done'
	 echo "+-------------------------------------------------+OK"

#Ativando Memcached
echo "Ativando Memcached - Sim/Nao"
read CONFIRMA
case $CONFIRMA in
s|S|Sim|sim)
$UsrZ 'zmprov -l ms `zmhostname` +zimbraServiceEnabled memcached'
		;;
n|N|Nao|nao)
$UsrZ 'zmprov -l ms `zmhostname` -zimbraServiceEnabled memcached'
		;;
*) echo  "Opcao Invalida" ;; esac
	 echo "+-------------------------------------------------+OK"

#Ativando Imapproxy e Proxy
echo "Ativando Imapproxy e Proxy - Sim/Nao"
read CONFIRMA
case $CONFIRMA in
s|S|Sim|sim)
$UsrZ 'zmprov -l ms `zmhostname` +zimbraServiceEnabled imapproxy'
$UsrZ 'zmprov -l ms `zmhostname` +zimbraServiceEnabled proxy'
$UsrZ 'zmprov -l mcf zimbraReverseProxyMailEnabled TRUE'
		;;
n|N|Nao|nao)
$UsrZ 'zmprov -l ms `zmhostname` -zimbraServiceEnabled imapproxy'
$UsrZ 'zmprov -l ms `zmhostname` -zimbraServiceEnabled proxy'
$UsrZ 'zmprov -l mcf zimbraReverseProxyMailEnabled FALSE'
		;;
*) echo  "Opcao Invalida" ;; esac
	 echo "+-------------------------------------------------+OK"

#Bloqueando Memcached Exploit
echo "Bloqueando Memcached Exploit"
$UsrZ 'zmprov -l ms `zmhostname` zimbraMemcachedBindAddress 127.0.0.1 '
$UsrZ 'zmprov -l ms `zmhostname` zimbraMemcachedClientServerList 127.0.0.1'
	 echo "+-------------------------------------------------+OK"

#Ativando AntiSpam
echo "Ativando AntiSpam - Sim/Nao"
read CONFIRMA
case $CONFIRMA in
s|S|Sim|sim)
$UsrZ 'zmprov -l ms `zmhostname` +zimbraServiceEnabled antispam'
		;;
n|N|Nao|nao)
$UsrZ 'zmprov -l ms `zmhostname` -zimbraServiceEnabled antispam'
		;;
*) echo  "Opcao Invalida" ;; esac
$UsrZ 'zmlocalconfig -e amavis_originating_bypass_sa=true'
$UsrZ 'zmlocalconfig -e antispam_enable_rule_updates=true'
$UsrZ 'zmlocalconfig -e antispam_enable_restarts=true'
$UsrZ 'zmlocalconfig -e antispam_enable_rule_compilation=true'
$UsrZ 'zmprov -l mcf zimbraAmavisOriginatingBypassSA TRUE'
$UsrZ 'zmprov -l mcf zimbraSpamKillPercent 90'
$UsrZ 'zmprov -l mcf zimbraSpamTagPercent 50'
$UsrZ 'zmprov -l mcf zimbraSpamSubjectTag "[*]"'
$UsrZ 'echo score DOS_OUTLOOK_TO_MX 0 > ~/data/spamassassin/localrules/sauser.cf'
$UsrZ 'echo score TO_EQ_FM_DIRECT_MX 0 >> ~/data/spamassassin/localrules/sauser.cf'
$UsrZ 'echo score RCVD_IN_PBL 0.1 >> ~/data/spamassassin/localrules/sauser.cf'
$UsrZ 'echo score RDNS_NONE 0.1 >> ~/data/spamassassin/localrules/sauser.cf'
$UsrZ 'echo score FREEMAIL_FORGED_REPLYTO 4.0 >> ~/data/spamassassin/localrules/sauser.cf'
$UsrZ 'echo use_bayes 0 >> ~/data/spamassassin/localrules/sauser.cf'
echo "Adicionar IP Publico do servidor a lista internal_networks do AntiSpam ex: `wget -qO - icanhazip.com`/32"
echo -n "IP Publico do Servidor: "
read IP
$UsrZ 'echo internal_networks '$IP' >> ~/data/spamassassin/localrules/sauser.cf'
$UsrZ '/opt/zimbra/libexec/zmspamextract -s -d -o /tmp/spam/' 1&> /dev/null
$UsrZ '/opt/zimbra/libexec/zmspamextract -n -d -o /tmp/notspam/' 1&> /dev/null
cd /opt/zimbra/data/spamassassin/localrules
wget -N https://www.pccc.com/downloads/SpamAssassin/contrib/KAM.cf -O sakam.cf 1&> /dev/null
echo "00 00 * * *"  zimbra  wget -N https://www.pccc.com/downloads/SpamAssassin/contrib/KAM.cf -O /opt/zimbra/data/spamassassin/localrules/sakam.cf > /etc/cron.d/sakam
	 echo "+-------------------------------------------------+OK"
#https://wiki.zimbra.com/wiki/Anti-spam_Strategies

#Adicionar IPs a Whitelist
echo "Adicionar IPs a Whitelist"
touch /opt/zimbra/conf/postfix_rbl_override 
echo '209.126.1.53    OK
209.126.1.83    OK
66.70.156.66    OK' > /opt/zimbra/conf/postfix_rbl_override
$UsrZ 'postmap /opt/zimbra/conf/postfix_rbl_override'
$UsrZ 'zmprov -l mcf +zimbraMtaRestriction 'check_client_access lmdb:/opt/zimbra/conf/postfix_rbl_override''
	 echo "+-------------------------------------------------+OK"
	 
#Adicionar IPs a Blacklist
#echo "Adicionar IPs a Blacklist"
#touch /opt/zimbra/conf/postfix_blacklist
#echo '209.126.1.53    OK
#209.126.1.83    OK
#66.70.156.66    OK' > /opt/zimbra/conf/postfix_rbl_override
#$UsrZ 'postmap /opt/zimbra/conf/postfix_blacklist'
#$UsrZ 'zmprov -l mcf +zimbraMtaRestriction 'check_client_access lmdb:/opt/zimbra/conf/postfix_blacklist''
	 echo "+-------------------------------------------------+OK"	 

#https://wiki.zimbra.com/wiki/Specific_Whitelist/Blacklist_per_IP

#Criando regras de proteção RBL
echo "Criando regras de proteção RBL"
$UsrZ 'zmprov -l mcf +zimbraMtaRestriction reject_unknown_sender_domain'
$UsrZ 'zmprov -l mcf +zimbraMtaRestriction "reject_rbl_client dnsbl.spfbl.net"'
$UsrZ 'zmprov -l mcf +zimbraMtaRestriction "reject_rbl_client dnsbl.sorbs.net"'
$UsrZ 'zmprov -l mcf +zimbraMtaRestriction "reject_rbl_client b.barracudacentral.org"'
$UsrZ 'zmprov -l mcf +zimbraMtaRestriction "reject_rbl_client psbl.surriel.com"'
$UsrZ 'zmprov -l mcf +zimbraMtaRestriction "reject_rbl_client cbl.abuseat.org"'
$UsrZ 'zmprov -l mcf +zimbraMtaRestriction "reject_rbl_client dnsbl.spfbl.net"'
$UsrZ 'zmprov -l mcf zimbraMtaPostscreenDnsblSites 'b.barracudacentral.org=127.0.0.2*7' zimbraMtaPostscreenDnsblSites 'dnsbl.sorbs.net=127.0.0.10*8' zimbraMtaPostscreenDnsblSites 'dnsbl.sorbs.net=127.0.0.5*6' zimbraMtaPostscreenDnsblSites 'dnsbl.sorbs.net=127.0.0.7*3' zimbraMtaPostscreenDnsblSites 'dnsbl.sorbs.net=127.0.0.8*2' zimbraMtaPostscreenDnsblSites 'dnsbl.sorbs.net=127.0.0.6*2' zimbraMtaPostscreenDnsblSites 'dnsbl.sorbs.net=127.0.0.9*2''
$UsrZ 'zmprov -l mcf zimbraMtaPostscreenDnsblAction enforce'
$UsrZ 'zmprov -l mcf zimbraMtaPostscreenGreetAction enforce'
$UsrZ 'zmprov -l mcf zimbraMtaPostscreenNonSmtpCommandAction drop'
$UsrZ 'zmprov -l mcf zimbraMtaPostscreenPipeliningAction enforce'
	 echo "+-------------------------------------------------+OK"
#https://www.missioncriticalemail.com/2019/03/21/zimbra-anti-spam-best-practices-2019/

#Ativando AntiVirus
echo "Ativando AntiVirus - Sim/Nao"
read CONFIRMA
case $CONFIRMA in
s|S|Sim|sim)
$UsrZ 'zmprov -l ms `zmhostname` +zimbraServiceEnabled amavis'
$UsrZ 'zmprov -l ms `zmhostname` +zimbraServiceEnabled antivirus'
$UsrZ 'zmprov -l mcf zimbraVirusDefinitionsUpdateFrequency 2h'
$UsrZ 'zmprov -l mcf zimbraAmavisLogLevel 2'
$UsrZ 'for dominios in $(zmprov -l gad); do zmprov -l md $dominios amaviswhitelistsender ""; done'
$UsrZ 'for dominios in $(zmprov -l gad); do zmprov -l md $dominios +amaviswhitelistsender $dominios; done'
$UsrZ 'for dominios in $(zmprov -l gad); do zmprov -l md $dominios +amaviswhitelistsender hostlp.com.br; done'
$UsrZ 'for dominios in $(zmprov -l gad); do zmprov -l md $dominios +amaviswhitelistsender hostlp.net; done'
$UsrZ 'for dominios in $(zmprov -l gad); do zmprov -l md $dominios +amaviswhitelistsender hostlp.cloud; done'
$UsrZ 'for dominios in $(zmprov -l gad); do zmprov -l md $dominios +amaviswhitelistsender microsoft.com; done'
$UsrZ 'for dominios in $(zmprov -l gad); do zmprov -l md $dominios +amaviswhitelistsender gmail.com; done'
$UsrZ 'for dominios in $(zmprov -l gad); do zmprov -l md $dominios +amaviswhitelistsender hotmail.com; done'
$UsrZ 'for dominios in $(zmprov -l gad); do zmprov -l md $dominios +amaviswhitelistsender account.microsoft.com; done'
$UsrZ 'for dominios in $(zmprov -l gad); do zmprov -l md $dominios +amaviswhitelistsender accountprotection.microsoft.com; done'
$UsrZ 'for dominios in $(zmprov -l gad); do zmprov -l md $dominios +amaviswhitelistsender accounts.google.com; done'
$UsrZ 'for dominios in $(zmprov -l gad); do zmprov -l md $dominios +amaviswhitelistsender fazenda.sp.gov.br; done'
$UsrZ 'for dominios in $(zmprov -l gad); do zmprov -l md $dominios +amaviswhitelistsender google.com; done'
$UsrZ 'for dominios in $(zmprov -l gad); do zmprov -l md $dominios +amaviswhitelistsender mercadolivre.com; done'
$UsrZ 'for dominios in $(zmprov -l gad); do zmprov -l md $dominios +amaviswhitelistsender mercadopago.com; done'
$UsrZ 'for dominios in $(zmprov -l gad); do zmprov -l md $dominios +amaviswhitelistsender outlook.com; done'
    echo "+-------------------------------------------------+OK"
        ;;
n|N|Nao|nao)
$UsrZ 'zmprov -l ms `zmhostname` -zimbraServiceEnabled amavis'
$UsrZ 'zmprov -l ms `zmhostname` -zimbraServiceEnabled antivirus'
    echo "+-------------------------------------------------+OK"
       ;;
*) echo  "Opcao Invalida" ;; esac
#https://www.missioncriticalemail.com/2019/03/21/zimbra-anti-spam-best-practices-2019/

#Adicionar IP Publibco do servidor a lista HttpThrottleSafeIPs
echo "Adicionar IP Publico do servidor a lista HttpThrottleSafeIPs ex: `wget -qO - icanhazip.com`/32"
echo -n "IP Publico do Servidor: "
read IP
$UsrZ 'zmprov -l mcf zimbraHttpThrottleSafeIPs 127.0.0.1/32 zimbraHttpThrottleSafeIPs '$IP''
$UsrZ 'zmprov -l ms `zmhostname` zimbraHttpThrottleSafeIPs 127.0.0.1/32 zimbraHttpThrottleSafeIPs '$IP''
    echo "+-------------------------------------------------+OK"

#Desativando alguns ZimLets
echo "Desativando alguns ZimLets"
$UsrZ 'zmzimletctl disable com_zextras_mailarchive' 1&> /dev/null
$UsrZ 'zmzimletctl disable com_zextras_webex' 1&> /dev/null
$UsrZ 'zmzimletctl disable com_zextras_ymemoticons' 1&> /dev/null

echo "Desativa Zimbra-Drive - Sim/Nao"
read CONFIRMA
case $CONFIRMA in
s|S|Sim|sim)
apt-get remove zimbra-drive --purge -y 1&> /dev/null
$UsrZ 'zmzimletctl disable com_zextras_drive_open' 1&> /dev/null
	 echo "+-------------------------------------------------+OK"
        ;;
n|N|Nao|nao)
apt-get install zimbra-drive -y 1&> /dev/null
$UsrZ 'zmzimletctl enable com_zextras_drive_open' 1&> /dev/null
	 echo "+-------------------------------------------------+OK"
       ;;
*) echo  "Opcao Invalida" ;; esac

echo "Desativa Zimbra-Chat - Sim/Nao"
read CONFIRMA
case $CONFIRMA in
s|S|Sim|sim)
apt-get remove zimbra-chat --purge -y 1&> /dev/null
$UsrZ 'zmzimletctl disable com_zextras_chat_open' 1&> /dev/null
	 echo "+-------------------------------------------------+OK"
        ;;
n|N|Nao|nao)
apt-get install zimbra-chat -y 1&> /dev/null
$UsrZ 'zmzimletctl enable com_zextras_chat_open' 1&> /dev/null
	 echo "+-------------------------------------------------+OK"
       ;;
*) echo  "Opcao Invalida" ;; esac

#Desativando Texto não Criptografado
echo "Desativando Texto não Criptografado"
$UsrZ 'zmprov -l ms `zmhostname` zimbraMailClearTextPasswordEnabled TRUE'
$UsrZ 'zmprov -l ms `zmhostname` zimbraImapCleartextLoginEnabled TRUE'
$UsrZ 'zmprov -l ms `zmhostname` zimbraPop3CleartextLoginEnabled TRUE'
$UsrZ 'zmprov -l ms `zmhostname` zimbraMtaTlsAuthOnly TRUE'
$UsrZ 'zmprov -l ms `zmhostname` zimbraMtaTlsSecurityLevel may'
$UsrZ 'zmprov -l mcf zimbraMailClearTextPasswordEnabled FALSE'
$UsrZ 'zmprov -l mcf zimbraImapCleartextLoginEnabled FALSE'
$UsrZ 'zmprov -l mcf zimbraImapCleartextLoginEnabled FALSE'
$UsrZ 'zmprov -l mcf zimbraPop3CleartextLoginEnabled FALSE'
$UsrZ 'zmprov -l mcf zimbraMtaTlsAuthOnly TRUE'
$UsrZ 'zmprov -l mcf zimbraMtaTlsSecurityLevel may'
$UsrZ 'zmlocalconfig -e postfix_smtp_tls_security_level=may'
	 echo "+-------------------------------------------------+OK"
#https://wiki.zimbra.com/wiki/SecureConfiguration

#Acertando problema no webmail com anexos
#echo "Acertando problema no webmail com anexos"
#$UsrZ 'zmlocalconfig -e zimbra_use_owasp_html_sanitizer=FALSE'
#	 echo "+-------------------------------------------------+OK"

#Aplicando regra de falso mail from
echo "Aplicando regra de falso mail from"
$UsrZ 'zmprov -l mcf zimbraMtaSmtpdRejectUnlistedRecipient yes'
$UsrZ 'zmprov -l mcf zimbraMtaSmtpdRejectUnlistedSender yes'
	 echo "+-------------------------------------------------+OK"
#https://wiki.zimbra.com/wiki/Rejecting_false_%22mail_from%22_addresses

#Aplicando regra usuario verdadeiro de FROM e SASL
echo "Aplicando regra usuario verdadeiro de FROM e SASL"
$UsrZ 'zmprov -l mcf zimbraMtaSmtpdSenderLoginMaps  proxy:ldap:/opt/zimbra/conf/ldap-slm.cf +zimbraMtaSmtpdSenderRestrictions reject_authenticated_sender_login_mismatch'
sed -i 's/^permit_mynetworks/permit_mynetworks, reject_sender_login_mismatch/g' /opt/zimbra/conf/zmconfigd/smtpd_sender_restrictions.cf
	 echo "+-------------------------------------------------+OK"
#https://wiki.zimbra.com/wiki/Enforcing_a_match_between_FROM_address_and_sasl_username_8.5
	 
#Alterando CharSet de todos COS
echo "Alterando CharSet de todos COS"
$UsrZ 'for cos in `zmprov -l gac`; do zmprov -l mc $cos zimbraPrefMailDefaultCharset UTF-8; done'
	 echo "+-------------------------------------------------+OK"

#Aplicando politica de DOSFilter
echo "Aplicando politica de DOSFilter"
$UsrZ 'zmprov -l mcf zimbraHttpDosFilterDelayMillis 20'
$UsrZ 'zmprov -l mcf zimbraHttpDosFilterMaxRequestsPerSec 100'
$UsrZ 'zmprov -l mcf zimbraInvalidLoginFilterDelayInMinBetwnReqBeforeReinstating 10'
$UsrZ 'zmprov -l mcf zimbraInvalidLoginFilterMaxFailedLogin 15'
$UsrZ 'zmprov -l mcf zimbraInvalidLoginFilterReinstateIpTaskIntervalInMin 5'
	 echo "+-------------------------------------------------+OK"
#https://wiki.zimbra.com/wiki/DoSFilter	 

#Aplicando Tunning de Conexões
echo "Aplicando Tunning de Conexões"
$UsrZ 'zmprov -l ms `zmhostname` zimbraHttpNumThreads 500'
$UsrZ 'zmprov -l ms `zmhostname` zimbraPop3NumThreads 200'
$UsrZ 'zmprov -l ms `zmhostname` zimbraPop3MaxConnections 400'
$UsrZ 'zmprov -l ms `zmhostname` zimbraImapNumThreads 2000'
$UsrZ 'zmprov -l ms `zmhostname` zimbraImapMaxConnections 2000'
$UsrZ 'zmprov -l mcf zimbraHttpNumThreads 500'
$UsrZ 'zmprov -l mcf zimbraPop3NumThreads 200'
$UsrZ 'zmprov -l mcf zimbraPop3MaxConnections 400'
$UsrZ 'zmprov -l mcf zimbraImapNumThreads 2000'
$UsrZ 'zmprov -l mcf zimbraImapMaxConnections 2000'
	 echo "+-------------------------------------------------+OK"

#Aplicando Tunning do Java servidor com 16GB Ram
echo "Aplicando Tunning do Java servidor com 16GB Ram"
$UsrZ 'zmlocalconfig -e mailboxd_java_heap_size=4096'
$UsrZ 'zmlocalconfig -e mailboxd_java_heap_memory_percent=25'
$UsrZ 'zmlocalconfig -e mailboxd_java_heap_new_size_percent=25'
$UsrZ 'zmlocalconfig -e zimbra_require_interprocess_security=0'
	 echo "+-------------------------------------------------+OK"

#Aplicar Tunning no MySQL
echo "Aplicar Tunning no MySQL..."
echo "Não esqueça de alterar o arquivo /opt/zimbra/conf/my.cnf no parametro innodb_buffer_pool_size conforme RAM disponivel"
echo "32GB - 13743895360  /  16GB - 6871947680  /  8GB - 3435973840"
	echo "Aperte <ENTER> para continuar e começar..."
	read 
	 echo "+-------------------------------------------------+OK"

#Aplicando Tunning de LMTP
echo "Aplicando Tunning de LMTP"
$UsrZ 'zmprov -l ms `zmhostname` zimbraLmtpNumThreads 40'
$UsrZ 'zmprov -l mcf zimbraLmtpNumThreads 40'
$UsrZ 'zmlocalconfig -e postfix_lmtp_destination_concurrency_limit=20'
	 echo "+-------------------------------------------------+OK"
#https://wiki.zimbra.com/wiki/Performance_Tuning_Guidelines_for_Large_Deployments

#Aplicando Spell em pt_BR
echo "Aplicando Spell em pt_BR"
$UsrZ 'zmprov -l ms `zmhostname` zimbraSpellAvailableDictionary pt_BR'
	 echo "+-------------------------------------------------+OK"

#Aplicando 30 dias de visibilidade de reuperação da lixeira
echo "Aplicando 30 dias de visibilidade de reuperação da lixeira"
$UsrZ 'zmprov -l mc default zimbraDumpsterUserVisibleAge 30d'
	 echo "+-------------------------------------------------+OK"

#Aplicando quanto tempo em dias armazenar os e-mails mais antigos
echo "Aplicando quanto tempo em dias armazenar os e-mails mais antigos (0 = ILIMITADO / Padrão HOSTLP 7200)"
echo -n "Digite em dias o tempo de vida dos e-mails do Dominio: "
read LIFETIME
$UsrZ 'zmprov -l mc default zimbraMailMessageLifetime "'$LIFETIME'"'
$UsrZ 'zmprov -l ms `zmhostname` zimbraMailPurgeSleepInterval 1m'
#https://wiki.zimbra.com/wiki/Mailbox_Purge
	 echo "+-------------------------------------------------+OK"

#Reescreve alterações
echo "Reescrevendo alterações"
$UsrZ 'zmmtactl restart'
$UsrZ 'zmconfigdctl restart'
	 echo "+-------------------------------------------------+OK"

#Arrumar permissões de pastas
echo "Arrumar permissões de pastas - Sim/Nao"
read CONFIRMA
case $CONFIRMA in
s|S|Sim|sim)
/opt/zimbra/libexec/zmfixperms -extended
		;;
n|N|Nao|nao)
       ;;
*) echo  "Opcao Invalida" ;; esac
	 echo "+-------------------------------------------------+OK"

#Reinicia Zimbra
	echo
	echo
	echo "Aperte <ENTER> para reiniciar o Zimbra..."
	read 
	sleep 5
	echo
	echo "===================PARANDO========================"
	echo
	echo "Parando o Zimbra"
$UsrZ 'zmcontrol stop'
	echo "+-------------------------------------------------+OK"
	echo
	echo
	echo "Aperte <ENTER> para Iniciar o Zimbra..."
	read 
	sleep 5
	echo
	echo "==================INICIANDO======================="
	echo
	echo "Iniciando o Zimbra"
$UsrZ 'zmcontrol start'
	echo "+-------------------------------------------------+OK"
	echo
	echo "Status do Zimbra"
$UsrZ 'zmcontrol status'
	echo "+-------------------------------------------------+OK"

echo "[`date`] ==== Fim de rotina..."
