#!/bin/bash
#+----------------GERANDO LOG-----------------------+OK"
SCRIPT=`basename $0`
LOG=`echo /opt/zimbra/$SCRIPT.log | sed s/'.sh'/'.log'/g`
exec &> >(tee -a "$LOG")
echo "[`date`] ==== Inicio de rotina..."
#+----------------GERANDO LOG-----------------------+OK"

clear

#Checa se o usuario é root
LOCAL_USER=`id -u -n`

if [ $LOCAL_USER != "root" ] ; then
	echo "     Rodar como usuario root"
	echo "     saindo..."
	echo ""
	exit
fi
	dir="Diretorio Atual		 : `pwd`"
	hostname="Hostname			 : `hostname --fqdn`"
	ip="IP						 : `ifconfig | awk 'NR>=2 && NR<=2' | awk '{print $3}'`"
    versaoso="Versao S.O.		 : `lsb_release -d | cut -d : -f 2- | sed 's/^[ \t]*//;s/[ \t]*$//'`"
	release="Release			 : `lsb_release -r | cut -d : -f 2- | sed 's/^[ \t]*//;s/[ \t]*$//'`"
	codename="Codename			 : `lsb_release -c | cut -d : -f 2- | sed 's/^[ \t]*//;s/[ \t]*$//'`"
	kernel="Kernel				 : `uname -r`"
	arquitetura="Arquitetura	 : `uname -m`"
	versaozimbra="Versao Zimbra : `su - zimbra -c 'zmcontrol -v'`"
    echo "+-------------------------------------------------+"
    echo "|       Utilitario para Zimbra com Avas  v1.1     |"
    echo "+-------------------------------------------------+"
    echo "+-------------------------------------------------+"
    echo "| Escrito por:                                    |"
    echo "| Thiago Castro - www.hostlp.net                  |"
    echo "+-------------------------------------------------+"
    echo
    echo $dir
	echo "+-------------------------------------------------+"
	echo $hostname
	echo "+-------------------------------------------------+"
	echo $ip
	echo "+-------------------------------------------------+"
	echo $versaoso
	echo "+-------------------------------------------------+"
	echo $release
	echo "+-------------------------------------------------+"
	echo $codename
	echo "+-------------------------------------------------+"
    echo $kernel
	echo "+-------------------------------------------------+"
    echo $arquitetura
	echo "+-------------------------------------------------+"
	echo $versaozimbra
	echo "+-------------------------------------------------+"
	echo
	echo "Aperte <ENTER> para continuar e começar..."
	read 
	sleep 5
	echo
	echo "==================EXECUTANDO======================="
	echo
	
#Variavel
UsrZ="su - zimbra -c"

echo "Download do Filtro - AVAS SPAM..."
	echo
	DEST="/tmp/`hostname`"
	mkdir $DEST -p
	cd $DEST
wget --no-check-certificate --no-cache --no-cookies -N https://raw.githubusercontent.com/thytetgc/Zimbra/master/filtro-avas-spam 1&> /dev/null
	echo "+-------------------------------------------------+OK"
	echo

echo "Exportando lista de usuarios..."
	echo
/opt/zimbra/bin/zmprov -l gaa | tee -a $DEST/usuarios
	echo "+-------------------------------------------------+OK"
	echo

echo "Exportando Filtros..."
	echo
	mkdir $DEST/filtros/ -p
for user in `cat $DEST/usuarios`; do
/opt/zimbra/bin/zmprov ga $user zimbraMailSieveScript > /tmp/filtrostemp
    sed -i -e "1d" /tmp/filtrostemp
    sed 's/zimbraMailSieveScript: //g' /tmp/filtrostemp  > $DEST/filtros/$user.filtros
    rm -f /tmp/filtrostemp
    echo "$user -- OK"
done 

echo "Mesclando os dois filtros..."
	echo
	sed -i '/require/d' $DEST/filtro-avas-spam
for user in $(/opt/zimbra/bin/zmprov -l gaa); do cat $DEST/filtro-avas-spam >> $DEST/filtros/$user.filtros ; done
#for users in `cat $DEST/usuarios`; do cat $DEST/filtro-avas-spam >> $DEST/filtros/$user.filtros ; done
	echo "+-------------------------------------------------+OK"
	echo

echo "Importando Filtros..."
	echo
for user in $(/opt/zimbra/bin/zmprov -l gaa); do /opt/zimbra/bin/zmprov ma $user zimbraMailSieveScript "`cat $DEST/filtros/$user.filtros`"; echo "$user -- OK"; done
#for user in `cat $DEST/usuarios`; do /opt/zimbra/bin/zmprov ma  $user zimbraMailSieveScript "`cat $DEST/filtros/$user.filtros`"; echo "$user -- OK"; done
	echo "+-------------------------------------------------+OK"
	echo

echo "[`date`] ==== Fim de rotina..."
