#!/bin/bash
#+----------------GERANDO LOG-----------------------+OK"
SCRIPT=`basename $0`
LOG=`echo /opt/zimbra/$SCRIPT.log | sed s/'.sh'/'.log'/g`
exec &> >(tee -a "$LOG")
echo "[`date`] ==== Inicio de rotina..."
#+----------------GERANDO LOG-----------------------+OK"

clear

#Checa se o usuario é root
LOCAL_USER=`id -u -n`

if [ $LOCAL_USER != "root" ] ; then
        echo "     Rodar como usuario root"
        echo "     saindo..."
        echo ""
        exit
fi
        dir="Diretorio Atual             : `pwd`"
        hostname="Hostname                       : `hostname --fqdn`"
        ip="IP                                           : `ifconfig | awk 'NR>=2 && NR<=2' | awk '{print $3}'`"
    versaoso="Versao S.O.                : `lsb_release -d | cut -d : -f 2- | sed 's/^[ \t]*//;s/[ \t]*$//'`"
        release="Release                         : `lsb_release -r | cut -d : -f 2- | sed 's/^[ \t]*//;s/[ \t]*$//'`"
        codename="Codename                       : `lsb_release -c | cut -d : -f 2- | sed 's/^[ \t]*//;s/[ \t]*$//'`"
        kernel="Kernel                           : `uname -r`"
        arquitetura="Arquitetura         : `uname -m`"
        versaozimbra="Versao Zimbra : `su - zimbra -c 'zmcontrol -v'`"
    echo "+-------------------------------------------------+"
     echo "|           Utilitario para Zimbra     v2.0      |"
    echo "+-------------------------------------------------+"
    echo "+-------------------------------------------------+"
    echo "| Escrito por:                                    |"
    echo "| Thiago Castro - www.hostlp.cloud                |"
    echo "+-------------------------------------------------+"
    echo
    echo $dir
        echo "+-------------------------------------------------+"
        echo $hostname
        echo "+-------------------------------------------------+"
        echo $ip
        echo "+-------------------------------------------------+"
        echo $versaoso
        echo "+-------------------------------------------------+"
        echo $release
        echo "+-------------------------------------------------+"
        echo $codename
        echo "+-------------------------------------------------+"
    echo $kernel
        echo "+-------------------------------------------------+"
    echo $arquitetura
        echo "+-------------------------------------------------+"
        echo $versaozimbra
        echo "+-------------------------------------------------+"
        echo
        echo "Aperte <ENTER> para continuar e começar..."
        read
        echo
        echo "==================EXECUTANDO======================="
        echo

#Variavel
UsrZ="su - zimbra -c"

#Copiar COS Default para o novo
echo "Copiando COS Default para o novo"
echo "+-------------------------------------------------+"
echo -n "Digite o nome do novo COS: "
read COSNOVO
NEWCOS="$COSNOVO"
$UsrZ 'zmprov cpc default "'$NEWCOS'"'
         echo "+-------------------------------------------------+OK"

echo -n "Digite a descrição do novo COS: "
read DESCRICAO
$UsrZ 'zmprov mc "'$NEWCOS'" description "'$DESCRICAO'"'
         echo "+-------------------------------------------------+OK"

echo "Alterar Quota padrão por usuario do dominio em bytes (1073741824 = 1GB / 2147483648 = 2GB / 3221225472 = 3GB / 4294967296 = 4GB / 5368709120 = 5GB / 0 = ILIMITADO)"
echo -n "Digite em bytes a quota do novo Dominio: "
read USRQUOTA
$UsrZ 'zmprov mc "'$NEWCOS'" zimbraMailQuota "'$USRQUOTA'"'
         echo "+-------------------------------------------------+OK"

echo "Ajustando o tempo de vida dos e-mails (0 = ILIMITADO / Padrão HOSTLP 7200)"
echo -n "Digite em dias o tempo de vida dos e-mails do Dominio: "
read LIFETIME
$UsrZ 'zmprov mc "'$NEWCOS'" zimbraMailMessageLifetime "'$LIFETIME'"'
$UsrZ 'zmprov ms `zmhostname` zimbraMailPurgeSleepInterval 1m'
         echo "+-------------------------------------------------+OK"

echo
echo
#Criar novo Dominio
echo "Criando novo Dominio"
echo "+-------------------------------------------------+"
echo -n "Digite o nome completo do Dominio: "
read DOMAINNOVO
NEWDOMAIN="$DOMAINNOVO"

# Verificar se NEWDOMAIN não está vazio
if [ -z "$NEWDOMAIN" ]; then
    echo "ERRO: Variável NEWDOMAIN está vazia!"
    echo "O script será interrompido."
    exit 1
fi

# Validar formato do domínio (se você quiser adicionar isso também)
if [[ ! "$NEWDOMAIN" =~ ^[a-zA-Z0-9][a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$ ]]; then
    echo "Erro: Formato de domínio inválido!"
    echo "O domínio deve estar no formato correto (exemplo: dominio.com.br)"
    echo "O script será interrompido."
    exit 1
fi

$UsrZ 'zmprov cd '$NEWDOMAIN''
         echo "+-------------------------------------------------+OK"

echo "Adicioando Dominio novo para o COS criado"
NCOS="`su - zimbra -c "zmprov gc '$NEWCOS' zimbraId|cut -d' ' -f2|egrep -v 'name|$^'"`"
$UsrZ 'zmprov md '$NEWDOMAIN' zimbraDomainDefaultCOSId '$NCOS''
#$UsrZ 'for NCOS in $(zmprov gc "'$NEWCOS'" zimbraId | cut -d' ' -f2 | grep -v name); do zmprov md '$NEWDOMAIN' zimbraDomainDefaultCOSId $NCOS; done'
#$UsrZ 'for NCOS in $(zmprov gc '$NEWCOS' zimbraId|awk '{print $2}'|egrep -v "name|$^"); do zmprov md "'$NEWDOMAIN'" zimbraDomainDefaultCOSId $NCOS; done'
         echo "+-------------------------------------------------+OK"

echo "Alterando Aviso de Quota para 90%"
$UsrZ 'zmprov md '$NEWDOMAIN' zimbraDomainAggregateQuotaWarnPercent 90'
         echo "+-------------------------------------------------+OK"

echo "Acertando Fuso Horario -0300"
$UsrZ 'zmprov md '$NEWDOMAIN' zimbraPrefTimeZoneId America/Sao_Paulo'
         echo "+-------------------------------------------------+OK"

echo "Acertando Protocolo"
$UsrZ 'zmprov md '$NEWDOMAIN' zimbraPublicServiceProtocol https'
         echo "+-------------------------------------------------+OK"

echo "Alterar Quota do dominio em bytes (10737418240 = 10GB / 21474836480 = 20GB / 32212254720 = 30GB / 42949672960 = 40GB / 53687091200 = 50GB)"
echo "Ou ENTER para ilimitado"
echo -n "Digite em bytes a quota do novo Dominio: "
read DOMANINQUOTA
$UsrZ 'zmprov md '$NEWDOMAIN' zimbraDomainAggregateQuota "'$DOMANINQUOTA'"'
         echo "+-------------------------------------------------+OK"

echo "Enviar e-mail de aviso de Quota para: "
echo -n "Digite o e-mail Completo: "
read EMAILQUOTA
$UsrZ 'zmprov md '$NEWDOMAIN' zimbraDomainAggregateQuotaWarnEmailRecipient '$EMAILQUOTA''
         echo "+-------------------------------------------------+OK"

echo "Politica de Quota agregada ao Dominio: "
$UsrZ 'zmprov md '$NEWDOMAIN' zimbraDomainAggregateQuotaPolicy BLOCKSENDRECEIVE'
         echo "+-------------------------------------------------+OK"

echo "Alterando nome do Compartilhamento do Porta Arquivos"
echo -n "Digite o nome do Compartilhamento do Porta Arquivos: "
read PORTAARQ
$UsrZ 'zmprov md '$NEWDOMAIN' zimbraBasicAuthRealm "'$PORTAARQ'"'
         echo "+-------------------------------------------------+OK"

echo "Criando usuario GALSYNC: "
$UsrZ 'zmgsautil createAccount -a galsync@'$NEWDOMAIN' -n '$NEWCOS' --domain '$NEWDOMAIN' -t zimbra -s `hostname --fqdn` -f '$NEWCOS''
$UsrZ 'zmgsautil forceSync -a galsync@'$NEWDOMAIN' -n '$NEWCOS''
$UsrZ 'zmprov mds galsync@'$NEWDOMAIN' '$NEWCOS' zimbraDataSourcePollingInterval 12h'

         echo "+-------------------------------------------------+OK"

echo
echo
#Ajustes Finos
echo "Ajustes finos"
echo "+-------------------------------------------------+"
echo "Alterando Logo"
$UsrZ 'zmprov md '$NEWDOMAIN' zimbraSkinLogoURL https://site.hostlp.com.br'
$UsrZ 'zmprov md '$NEWDOMAIN' zimbraSkinLogoLoginBanner https://site.hostlp.com.br/imagens/zimbra/Logotipo_Novo_130x58.png'
$UsrZ 'zmprov md '$NEWDOMAIN' zimbraSkinLogoAppBanner https://site.hostlp.com.br/imagens/zimbra/Logotipo_Novo_80x36.png'
         echo "+-------------------------------------------------+OK"

echo "Limitar usuarios para o Dominio"
echo -n "Quantas contas? "
read QTSCONTAS
$UsrZ 'zmprov md '$NEWDOMAIN' zimbraDomainMaxAccounts '$QTSCONTAS''
         echo "+-------------------------------------------------+OK"

echo "Alterando CharSet do COS"
$UsrZ 'zmprov mc '$NEWCOS' zimbraPrefMailDefaultCharset UTF-8'
         echo "+-------------------------------------------------+OK"

echo "Adicionando os subdomínios dinamicamente (baseado no nome do host)"
for sub in mail pop imap smtp webmail; do
    $UsrZ "zmprov md '$NEWDOMAIN' +zimbraVirtualHostname '$sub.$NEWDOMAIN'"
    echo "   Adicionado subdomínio: $sub.$NEWDOMAIN"
done
        echo "+-------------------------------------------------+OK"

echo "Configurando protocolo, porta e hostname público"
$UsrZ "zmprov md '$NEWDOMAIN' zimbraPublicServiceProtocol https"
$UsrZ "zmprov md '$NEWDOMAIN' zimbraPublicServicePort 443"
$UsrZ "zmprov md '$NEWDOMAIN' zimbraPublicServiceHostname 'mail.$NEWDOMAIN'"
        echo "+-------------------------------------------------+OK"

echo "Criando DKIM"
$UsrZ '/opt/zimbra/libexec/zmdkimkeyutil -a -d '$NEWDOMAIN''
         echo "+-------------------------------------------------+OK"

echo "Registrando DKIM:"
$UsrZ "/opt/zimbra/libexec/zmdkimkeyutil -q -d '$NEWDOMAIN'"
         echo "+-------------------------------------------------+OK"

echo
echo
echo "Aperte <ENTER> para finalizar..."
read

echo "[`date`] ==== Fim de rotina..."
