#!/bin/bash
#+----------------GERANDO LOG-----------------------+OK"
SCRIPT=`basename $0`
LOG=`echo /opt/zimbra/$SCRIPT.log | sed s/'.sh'/'.log'/g`
exec &> >(tee -a "$LOG")
echo "[`date`] ==== Inicio de rotina..."
#+----------------GERANDO LOG-----------------------+OK"

clear

#Checa se o usuario é root
LOCAL_USER=`id -u -n`

if [ $LOCAL_USER != "root" ] ; then
	echo "     Rodar como usuario root"
	echo "     saindo..."
	echo ""
	exit
fi
	dir="Diretorio Atual		 : `pwd`"
	hostname="Hostname			 : `hostname --fqdn`"
	ip="IP						 : `ifconfig | awk 'NR>=2 && NR<=2' | awk '{print $3}'`"
    versaoso="Versao S.O.		 : `lsb_release -d | cut -d : -f 2- | sed 's/^[ \t]*//;s/[ \t]*$//'`"
	release="Release			 : `lsb_release -r | cut -d : -f 2- | sed 's/^[ \t]*//;s/[ \t]*$//'`"
	codename="Codename			 : `lsb_release -c | cut -d : -f 2- | sed 's/^[ \t]*//;s/[ \t]*$//'`"
	kernel="Kernel				 : `uname -r`"
	arquitetura="Arquitetura	 : `uname -m`"
	versaozimbra="Versao Zimbra : `su - zimbra -c 'zmcontrol -v'`"
    echo "+-------------------------------------------------+"
    echo "|           Utilitario para Zimbra  v1.1          |"
    echo "+-------------------------------------------------+"
    echo "+-------------------------------------------------+"
    echo "| Escrito por:                                    |"
    echo "| Thiago Castro - www.hostlp.cloud                |"
    echo "+-------------------------------------------------+"
    echo
    echo $dir
	echo "+-------------------------------------------------+"
	echo $hostname
	echo "+-------------------------------------------------+"
	echo $ip
	echo "+-------------------------------------------------+"
	echo $versaoso
	echo "+-------------------------------------------------+"
	echo $release
	echo "+-------------------------------------------------+"
	echo $codename
	echo "+-------------------------------------------------+"
    echo $kernel
	echo "+-------------------------------------------------+"
    echo $arquitetura
	echo "+-------------------------------------------------+"
	echo $versaozimbra
	echo "+-------------------------------------------------+"
	echo
	echo "Aperte <ENTER> para continuar e começar..."
	read 
	sleep 5
	echo
	echo "==================EXECUTANDO======================="
	echo

clear
	
#Variavel
UsrZ="su - zimbra -c"

echo "Digite o nome do domínio"
echo -n "Domínio: "
read DOMINIO
echo

echo "Digite o e-mail do usuário"
echo -n "Usuário: "
read USUARIOS
echo

echo "Aperte <ENTER> para continuar e começar..."
read 


echo "Aplicando regras..."
$UsrZ 'zmprov ma '$USUARIOS' zimbraIsDelegatedAdminAccount TRUE'
$UsrZ 'zmprov ma '$USUARIOS' zimbraAdminConsoleUIComponents accountListView zimbraAdminConsoleUIComponents downloadsView zimbraAdminConsoleUIComponents DLListView zimbraAdminConsoleUIComponents aliasListView zimbraAdminConsoleUIComponents resourceListView'
$UsrZ 'zmprov grr global usr '$USUARIOS' adminLoginCalendarResourceAs'
$UsrZ 'zmprov grr global usr '$USUARIOS' domainAdminZimletRights'
$UsrZ 'zmprov grr domain '$DOMINIO' usr '$USUARIOS' domainAdminRights'
$UsrZ 'zmprov grr domain '$DOMINIO' usr '$USUARIOS' domainAdminConsoleRights'
$UsrZ 'zmprov grr domain '$DOMINIO' usr '$USUARIOS' adminConsoleAliasRights'
$UsrZ 'zmprov grr domain '$DOMINIO' usr '$USUARIOS' modifyAccount'
$UsrZ 'zmprov grr domain '$DOMINIO' usr '$USUARIOS' countAlias'
$UsrZ 'zmprov grr domain '$DOMINIO' usr '$USUARIOS' configureQuota'
$UsrZ 'zmprov grr domain '$DOMINIO' usr '$USUARIOS' getMailboxInfo'
$UsrZ 'zmprov grr domain '$DOMINIO' usr '$USUARIOS' -configureAdminUI'
$UsrZ 'zmprov grr domain '$DOMINIO' usr '$USUARIOS' -get.account.zimbraAdminConsoleUIComponents'
$UsrZ 'zmprov grr domain '$DOMINIO' usr '$USUARIOS' -get.dl.zimbraAdminConsoleUIComponents'
$UsrZ 'zmprov grr domain '$DOMINIO' usr '$USUARIOS' -set.account.zimbraIsDelegatedAdminAccount'
$UsrZ 'zmprov grr domain '$DOMINIO' usr '$USUARIOS' -set.dl.zimbraIsAdminGroup'
echo

echo "Pode visualizaar e-mails? - Sim/Nao"
read CONFIRMA
case $CONFIRMA in
s|S|Sim|sim)
$UsrZ 'zmprov grr domain '$DOMINIO' usr '$USUARIOS' +adminLoginAs'
		;;
n|N|Nao|nao)
$UsrZ 'zmprov grr domain '$DOMINIO' usr '$USUARIOS' -adminLoginAs'
		;;
*) echo  "Opcao Invalida" ;; esac
echo

echo "Pode visualizar dominios? - Sim/Nao"
read CONFIRMA
case $CONFIRMA in
s|S|Sim|sim)
$UsrZ 'zmprov ma '$USUARIOS' zimbraAdminConsoleUIComponents domainListView zimbraAdminConsoleUIComponents accountListView zimbraAdminConsoleUIComponents downloadsView zimbraAdminConsoleUIComponents DLListView zimbraAdminConsoleUIComponents aliasListView zimbraAdminConsoleUIComponents resourceListView'
		;;
n|N|Nao|nao)
$UsrZ 'zmprov ma '$USUARIOS' zimbraAdminConsoleUIComponents accountListView zimbraAdminConsoleUIComponents downloadsView zimbraAdminConsoleUIComponents DLListView zimbraAdminConsoleUIComponents aliasListView zimbraAdminConsoleUIComponents resourceListView'
		;;
*) echo  "Opcao Invalida" ;; esac
echo

echo "[`date`] ==== Fim de rotina..."
