#!/bin/bash

#+----------------GERANDO LOG-----------------------+OK"
SCRIPT=`basename $0`
LOG=`echo $DEST/$SCRIPT.log | sed s/'.sh'/'.log'/g`
exec &> >(tee -a "$LOG")
echo "[`date`] ==== Inicio de rotina..."
#+----------------GERANDO LOG-----------------------+OK"

cd /tmp/
clear

#Checa se o usuario é zimbra
LOCAL_USER=`id -u -n`

if [ $LOCAL_USER != "zimbra" ] ; then
	echo "     Rodar como usuario Zimbra"
	echo "     saindo..."
	echo ""
	exit
fi

	clear
     dir="Diretorio Atual		 : `pwd`"
	 hostname="Hostname			 : `hostname --fqdn`"
	 ip="IP						 : `ifconfig | awk 'NR>=2 && NR<=2' | awk '{print $3}'`"
     versaoso="Versao S.O.		 : `lsb_release -d | cut -d : -f 2- | sed 's/^[ \t]*//;s/[ \t]*$//'`"
	 release="Release			 : `lsb_release -r | cut -d : -f 2- | sed 's/^[ \t]*//;s/[ \t]*$//'`"
	 codename="Codename			 : `lsb_release -c | cut -d : -f 2- | sed 's/^[ \t]*//;s/[ \t]*$//'`"
	 kernel="Kernel				 : `uname -r`"
	 arquitetura="Arquitetura	 : `uname -m`"
	 versaozimbra="Versao Zimbra : `/opt/zimbra/bin/zmcontrol -v`"
	 echo
     echo "+-------------------------------------------------+"
     echo "|           Utilitario para Zimbra                |"
     echo "+-------------------------------------------------+"
     echo "| 		Exportar Contas do Zimbra v1.14          |"
     echo "+-------------------------------------------------+"
     echo "| Escrito por:                                    |"
     echo "| Thiago Castro - www.hostlp.cloud                |"
     echo "+-------------------------------------------------+"
     echo
     echo $dir
	 echo "+-------------------------------------------------+"
	 echo $hostname
	 echo "+-------------------------------------------------+"
	 echo $ip
	 echo "+-------------------------------------------------+"
	 echo $versaoso
	 echo "+-------------------------------------------------+"
	 echo $release
	 echo "+-------------------------------------------------+"
	 echo $codename
	 echo "+-------------------------------------------------+"
     echo $kernel
	 echo "+-------------------------------------------------+"
     echo $arquitetura
	 echo "+-------------------------------------------------+"
	 echo $versaozimbra
	 echo "+-------------------------------------------------+"
	 echo
     sleep 5
	 echo
	 echo "==================EXECUTANDO======================="
	 echo


# EXPORTAÇÃO TOTAL
	source /opt/zimbra/bin/zmshutil
	zmsetvars
	zmprov=/opt/zimbra/bin/zmprov
	zmmailbox=/opt/zimbra/bin/zmmailbox
	ldapsearch=/opt/zimbra/common/bin/ldapsearch
	cd /opt/zimbra/backup/
	HOST=`hostname -d`
	DEST="/opt/zimbra/backup/"
	mv -rf $DEST tmp/$DOMAIN-BKP-$(date "+%Y%m%d") 2>/dev/null
	mkdir $DEST/cos $DEST/dominio $DEST/contas $DEST/contatos $DEST/listas $DEST/alias $DEST/assinaturas $DEST/filtros $DEST/briefcase $DEST/agendas -p 2>/dev/null
	chown zimbra:zimbra $DEST -R
	echo "+-------------------------------------------------+OK"
	
#######################################################

	echo "Exportando COS..."
	echo
ldapsearch -x -H $ldap_master_url -D $zimbra_ldap_userdn -w $zimbra_ldap_password -b '' -LLL "(objectclass=zimbraCOS)" > $DEST/cos/cos.ldiff
	echo "+-------------------------------------------------+OK"
	echo

	echo "Exportando Dominios..."
	echo
	rm -rf $DEST/dominio/dominio
zmprov gad | tee -a $DEST/dominio/dominio
	echo "+-------------------------------------------------+OK"
	echo
	
	echo "Exportando Contas..."
	echo
	rm -rf $DEST/contas/*
	zmhostname > $DEST/server_old
zmprov -l gaaa | egrep -v "^virus|^ham|^spam|^galsync" > $DEST/contas/admins
zmprov -l gaa | egrep -v "^virus|^ham|^spam|^galsync" > $DEST/contas/usuarios
for user in `cat $DEST/contas/usuarios`; do $ldapsearch -x -H $ldap_master_url -D $zimbra_ldap_userdn -w $zimbra_ldap_password -b '' -LLL "(zimbraMailDeliveryAddress=$user)" > $DEST/contas/$user.ldiff ; echo "$user -- OK" ; done
	echo "+-------------------------------------------------+OK"
	echo

	echo "Exportando Contatos..."
	echo
zmprov -l gaa | egrep -v "^virus|^ham|^spam|^galsync" | while read user; do zmmailbox -z -m $user gru "/Contacts" > $DEST/contatos/"$user".csv ; zmmailbox -z -m $user gru "/Emailed Contacts" > $DEST/contatos/"$user".emailed.csv ; echo "$user -- OK" ; done
	echo "+-------------------------------------------------+OK"
	echo

	echo "Exportando Briefcase..."
	echo
zmprov -l gaa | egrep -v "^virus|^ham|^spam|^galsync" | while read user; do zmmailbox -z -m $user gru "/Briefcase/?fmt=tgz" > $DEST/briefcase/"$user".tgz ; echo "$user -- OK" ; done 2>/dev/null
	echo "+-------------------------------------------------+OK"
	echo

	echo "Exportando Agendas..."
	echo
	cd $DEST/agendas
zmprov -l gaa | egrep -v "^virus|^ham|^spam|^galsync" | while read user; do zmmailbox -z -m $user gru "/Calendar?fmt=ics" > $DEST/agendas/"$user".ics ; echo "$user -- OK" ; done 2>/dev/null
	echo "+-------------------------------------------------+OK"
	echo
	
	echo "Exportando Listas de Distribuição..."
	echo
zmprov gadl > $DEST/listas/listas
zmprov gadl | while read user_listas; do zmprov gdlm $user_listas > $DEST/listas/$user_listas ; echo "$user_listas -- OK" ; done
	echo "+-------------------------------------------------+OK"
	echo

	echo "Exportando Alias..."
	echo
zmprov -l gaa | egrep -v "^virus|^ham|^spam|^galsync" | while read user; do zmprov ga $user | grep zimbraMailAlias | awk '{print $2}' > $DEST/alias/$user ; echo "$user -- OK" ; done
	echo "+-------------------------------------------------+OK"
	echo

	echo "Exportando Assinaturas..."
	echo
zmprov -l gaa | egrep -v "^virus|^ham|^spam|^galsync" | while read user; do zmprov gsig $user > $DEST/assinaturas/"$user" ; echo "$user -- OK" ; done
	sed -i '/zimbraSignatureId/d' $DEST/assinaturas/"$user" ;
	sed -i '/# name/d' $DEST/assinaturas/"$user" ;
	echo "+-------------------------------------------------+OK"
	echo

	echo "Exportando Filtros..."
	echo
for user in `cat $DEST/contas/usuarios`; do $zmprov ga $user zimbraMailSieveScript > /tmp/filtros
    sed -i -e "1d" /tmp/filtros
    sed 's/zimbraMailSieveScript: //g' /tmp/filtros  > $DEST/filtros/$user.filtros
    echo "$user -- OK" ; done  
	echo "+-------------------------------------------------+OK"
	echo
	
	echo "Limpando arquivos vazios..."
	echo
	find $DEST/ -type f -empty -exec rm -rf {} \;
	find $DEST/ -type f -empty -exec rm -rf {} \;
	chown zimbra:zimbra $DEST -R
	echo "Dados Exportados"
 
echo "[`date`] ==== Fim da rotina..."

