#!/bin/bash

#+----------------GERANDO LOG-----------------------+OK"
SCRIPT=`basename $0`
LOG=`echo $DEST/$SCRIPT.log | sed s/'.sh'/'.log'/g`
exec &> >(tee -a "$LOG")
echo "[`date`] ==== Inicio de rotina..."
#+----------------GERANDO LOG-----------------------+OK"

cd /tmp/
clear

#Checa se o usuario é zimbra
LOCAL_USER=`id -u -n`

if [ $LOCAL_USER != "zimbra" ] ; then
	echo "     Rodar como usuario Zimbra"
	echo "     saindo..."
	echo ""
	exit
fi
Principal() {
	clear
     dir="Diretorio Atual		 : `pwd`"
	 hostname="Hostname			 : `hostname --fqdn`"
	 ip="IP						 : `ifconfig | awk 'NR>=2 && NR<=2' | awk '{print $3}'`"
     versaoso="Versao S.O.		 : `lsb_release -d | cut -d : -f 2- | sed 's/^[ \t]*//;s/[ \t]*$//'`"
	 release="Release			 : `lsb_release -r | cut -d : -f 2- | sed 's/^[ \t]*//;s/[ \t]*$//'`"
	 codename="Codename			 : `lsb_release -c | cut -d : -f 2- | sed 's/^[ \t]*//;s/[ \t]*$//'`"
	 kernel="Kernel				 : `uname -r`"
	 arquitetura="Arquitetura	 : `uname -m`"
	 versaozimbra="Versao Zimbra : `/opt/zimbra/bin/zmcontrol -v`"
	 echo
     echo "+-------------------------------------------------+"
     echo "|           Utilitario para Zimbra                |"
     echo "+-------------------------------------------------+"
     echo "| Exportar / Importar Contas do Zimbra    v1.14   |"
     echo "+-------------------------------------------------+"
     echo "| Escrito por:                                    |"
     echo "| Thiago Castro - www.hostlp.cloud                |"
     echo "+-------------------------------------------------+"
     echo
     echo $dir
	 echo "+-------------------------------------------------+"
	 echo $hostname
	 echo "+-------------------------------------------------+"
	 echo $ip
	 echo "+-------------------------------------------------+"
	 echo $versaoso
	 echo "+-------------------------------------------------+"
	 echo $release
	 echo "+-------------------------------------------------+"
	 echo $codename
	 echo "+-------------------------------------------------+"
     echo $kernel
	 echo "+-------------------------------------------------+"
     echo $arquitetura
	 echo "+-------------------------------------------------+"
	 echo $versaozimbra
	 echo "+-------------------------------------------------+"
	 echo
	 echo "Este script irá exportar ou importar os dados de: "
	 echo "--> COS, dominios, contas, contatos, agendas, listas,"
	 echo "alias, assinaturas, filtros e briefcase <--"
	 echo "+-------------------------------------------------+"
     echo
	 echo "Aperte <ENTER> para continuar e começar..."
	 read 
	 echo "Opções:"
	 echo
     echo "1. Exportar"
	 echo "2. Importar"
	 echo
	 echo "3. Sair"
	 echo
	 echo
     echo -n "Entre com a opcao desejada => "
     read opcao
     echo
     case $opcao in
        1) Exportar1 ;;
        2) Importar1 ;;
        3) exit ;;
        *) "Opcao desconhecida." ; echo ; Principal ;;
     esac
}

Exportar1() {
# EXPORTAÇÃO POR DOMINIO
	clear
	source /opt/zimbra/bin/zmshutil
	zmsetvars
	zmprov=/opt/zimbra/bin/zmprov
	zmmailbox=/opt/zimbra/bin/zmmailbox
	ldapsearch=/opt/zimbra/common/bin/ldapsearch
	echo "Digite o dominio completo para exportar os dados ou deixe vazio"
	echo "para exportar os dados de todos os dominios cadastrados"
	echo
	echo -n "Digite o dominio completo...: "
	read DOMAIN
	echo
	cd /opt/zimbra/backup/
	HOST=`hostname -d`
	DEST="/opt/zimbra/backup/"$DOMAIN""
	mv -rf $DEST tmp/$DOMAIN-BKP-$(date "+%Y%m%d") 2>/dev/null
	mkdir $DEST/cos $DEST/dominio $DEST/contas $DEST/contatos $DEST/listas $DEST/alias $DEST/assinaturas $DEST/filtros $DEST/briefcase $DEST/agendas -p 2>/dev/null
	chown zimbra:zimbra $DEST -R
	echo "+-------------------------------------------------+OK"

#######################################################
		
	echo "Exportar todas COS? - Sim/Nao"
	read CONFIRMA
	case $CONFIRMA in
	s|S|Sim|sim)
ldapsearch -x -H $ldap_master_url -D $zimbra_ldap_userdn -w $zimbra_ldap_password -b '' -LLL "(objectclass=zimbraCOS)" > $DEST/cos/cos.ldiff
		;;
	n|N|Nao|nao)
	echo -n "Digite o nome do COS...: "
	read COS
	echo
ldapsearch -x -H $ldap_master_url -D $zimbra_ldap_userdn -w $zimbra_ldap_password -b '' -LLL "(objectclass=zimbraCOS)" > $DEST/cos/"$COS".ldiff
	sed -i '/cn='$COS'/,$!d' $DEST/cos/"$COS".ldiff
	sed -i '/^$/,$d' $DEST/cos/"$COS".ldiff
		;;
	*) echo  "Opcao Invalida" ;; esac
	echo "+-------------------------------------------------+OK"
	echo
	
	echo "Exportando Dominio..."
	echo
	rm -rf $DEST/dominio/dominio
zmprov gad | grep "$DOMAIN" | tee -a $DEST/dominio/dominio
	echo "+-------------------------------------------------+OK"
	echo
	
	echo "Exportando Contas..."
	echo
	rm -rf $DEST/contas/*
	zmhostname > $DEST/server_old
zmprov -l gaaa |grep "$DOMAIN" | egrep -v "^virus|^ham|^spam|^galsync" > $DEST/contas/admins
zmprov -l gaa |grep "$DOMAIN" | egrep -v "^virus|^ham|^spam|^galsync" > $DEST/contas/usuarios
for user in `cat $DEST/contas/usuarios`; do ldapsearch -x -H $ldap_master_url -D $zimbra_ldap_userdn -w $zimbra_ldap_password -b '' -LLL "(zimbraMailDeliveryAddress=$user)" > $DEST/contas/$user.ldiff ; echo "$user -- OK" ; done
	echo "+-------------------------------------------------+OK"
	echo

	echo "Exportar dados de caixa postal? (tgz) - Sim/Nao"
	read CONFIRMA
	case $CONFIRMA in
	s|S|Sim|sim)
zmprov -l gaa |grep "$DOMAIN" | egrep -v "^virus|^ham|^spam|^galsync" | while read user; do zmmailbox -z -m $user gru "/?fmt=tgz" > $DEST/contas/"$user".tgz ; echo "$user -- OK" ; done
		;;
	n|N|Nao|nao)
		;;
	*) echo  "Opcao Invalida" ;; esac
	echo "+-------------------------------------------------+OK"
	echo
	
	echo "Exportando Contatos..."
	echo
zmprov -l gaa |grep "$DOMAIN" | egrep -v "^virus|^ham|^spam|^galsync" | while read user; do zmmailbox -z -m $user gru "/Contacts" > $DEST/contatos/"$user".csv ; zmmailbox -z -m $user gru "/Emailed Contacts" > $DEST/contatos/"$user".emailed.csv ; echo "$user -- OK" ; done
	echo "+-------------------------------------------------+OK"
	echo

	echo "Exportando Briefcase..."
	echo
zmprov -l gaa |grep "$DOMAIN" | egrep -v "^virus|^ham|^spam|^galsync" | while read user; do zmmailbox -z -m $user gru "/Briefcase/?fmt=tgz" > $DEST/briefcase/"$user".tgz ; echo "$user -- OK" ; done 2>/dev/null
	echo "+-------------------------------------------------+OK"
	echo

	echo "Exportando Agendas..."
	echo
	cd $DEST/agendas
zmprov -l gaa |grep "$DOMAIN" | egrep -v "^virus|^ham|^spam|^galsync" | while read user; do zmmailbox -z -m $user gru "/Calendar?fmt=ics" > $DEST/agendas/"$user".ics ; echo "$user -- OK" ; done 2>/dev/null
	echo "+-------------------------------------------------+OK"
	echo
	
	echo "Exportando Listas de Distribuição..."
	echo
zmprov gadl "$DOMAIN" > $DEST/listas/listas
zmprov gadl "$DOMAIN" | while read user_listas; do zmprov gdlm $user_listas > $DEST/listas/$user_listas ; echo "$user_listas -- OK" ; done
	echo "+-------------------------------------------------+OK"
	echo

	echo "Exportando Alias..."
	echo
zmprov -l gaa |grep "$DOMAIN" | egrep -v "^virus|^ham|^spam|^galsync" | while read user; do zmprov ga $user | grep zimbraMailAlias | awk '{print $2}' > $DEST/alias/$user ; echo "$user -- OK" ; done
	echo "+-------------------------------------------------+OK"
	echo

	echo "Exportando Assinaturas..."
	echo
zmprov -l gaa |grep "$DOMAIN" | egrep -v "^virus|^ham|^spam|^galsync" | while read user; do zmprov gsig $user > $DEST/assinaturas/"$user" ; echo "$user -- OK" ; done
	sed -i '/zimbraSignatureId/d' $DEST/assinaturas/"$user" ;
	sed -i '/# name/d' $DEST/assinaturas/"$user" ;
	echo "+-------------------------------------------------+OK"
	echo

	echo "Exportando Filtros..."
	echo
for user in `cat $DEST/contas/usuarios`; do
zmprov ga $user zimbraMailSieveScript > /tmp/filtros
    sed -i -e "1d" /tmp/filtros
    sed 's/zimbraMailSieveScript: //g' /tmp/filtros  > $DEST/filtros/$user.filtros
    echo "$user -- OK" ; done 
	echo "+-------------------------------------------------+OK"
	echo

	echo "Limpando arquivos vazios..."
	echo
	find $DEST/ -type f -empty -exec rm -rf {} \;
	find $DEST/ -type f -empty -exec rm -rf {} \;
	chown zimbra:zimbra $DEST -R
	echo "Dados Exportados"
    echo "Pressione qualquer tecla para continuar..."
    read msg
    Principal
}

##########################################################################################################

Importar1() {
# IMPORTAÇÂO POR DOMINIO
# já com todos os dados no novo servidor
	clear
	source ~/bin/zmshutil
	zmsetvars
	echo "Importar todo os dados de um dominio"
	echo -n "Digite dominio completo...: "
	read DOMAIN
	echo
	cd /opt/zimbra/backup/
	HOST=`hostname -d`
	DEST="/opt/zimbra/backup/"$DOMAIN""
	chown zimbra:zimbra $DEST -R
		
#######################################################

	echo "Importar todas COS? - Sim/Nao"
	read CONFIRMA
	case $CONFIRMA in
	s|S|Sim|sim)
ldapadd -c -x -H $ldap_master_url -D $zimbra_ldap_userdn -w $zimbra_ldap_password -f $DEST/cos/cos.ldiff
		;;
	n|N|Nao|nao)
	echo -n "Digite o nome da COS...: "
	read COS
	echo
ldapadd -c -x -H $ldap_master_url -D $zimbra_ldap_userdn -w $zimbra_ldap_password -f $DEST/cos/"$COS".ldiff
		;;
	*) echo  "Opcao Invalida" ;; esac
	echo "+-------------------------------------------------+OK"
	echo

	echo "Importando Dominios..."
	echo
for domain in `cat $DEST/dominio/dominio`; do zmprov cd $domain zimbraAuthMech zimbra 2>/dev/null ; echo $domain ;done
	echo "+-------------------------------------------------+OK"
	echo

	echo "Limpando arquivos vazios..."
	echo
	cd $DEST
	find $DEST -type f -empty -exec rm -rf {} \;
	find $DEST -type f -empty -exec rm -rf {} \;
	echo "+-------------------------------------------------+OK"
	echo

	echo "Importando Contas..."
	echo
	SERVEROL="`cat $DEST/server_old`"
	SERVERNE="`zmhostname`"
	find $DEST -type f -name '*.ldiff' -exec sed -i "s/$SERVEROL/$SERVERNE/g" "{}" \;
for user in `cat $DEST/contas/usuarios`; do ldapadd -x -H $ldap_master_url -D $zimbra_ldap_userdn -c -w $zimbra_ldap_password -f $DEST/contas/$user.ldiff 2>/dev/null ; echo "$user -- OK" ; done
	echo "+-------------------------------------------------+OK"
	echo

	echo "Importar dados de caixa postal? - Sim/Nao"
	echo "Local da importação -> "$DEST/contas/...tgz""
	read CONFIRMA
	case $CONFIRMA in
	s|S|Sim|sim)
for user in `cat $DEST/contas/usuarios`; do zmmailbox -z -m $user postRestURL "/?fmt=tgz&resolve=skip" $DEST/contas/$user.tgz ; echo "$user -- OK" ; done
		;;
n|N|Nao|nao)
		;;
*) echo  "Opcao Invalida" ;; esac
	echo "+-------------------------------------------------+OK"
	echo
	
	echo "Importando Contatos..."
	echo
for user in $(ls $DEST/contatos |awk -F ".csv" '{print $1}') ; do zmmailbox -z -m $user pru "/Contacts" $DEST/contatos/"$user".csv ; echo "$user -- OK" ; done
for user in $(ls $DEST/contatos |awk -F ".emailed.csv" '{print $1}') ; do zmmailbox -z -m $user pru "/Emailed Contacts" $DEST/contatos/"$user".emailed.csv ; done
	echo "+-------------------------------------------------+OK"
	echo

	echo "Importando Briefcase..."
	echo
for user in $(ls $DEST/briefcase |awk -F ".tgz" '{print $1}') ; do zmmailbox -z -m $user pru "/Briefcase/?fmt=tgz" $DEST/briefcase/"$user".tgz ; echo "$user -- OK" ; done 2>/dev/null
	echo "+-------------------------------------------------+OK"
	echo

	echo "Importando Agendas..."
	echo
	cd $DEST/agendas
	#find . -type f -size -95c -exec rm -f {} \;
for user in $(ls |awk -F ".ics" '{print $1}') ; do zmmailbox -z -m $user pru /Calendar $DEST/agendas/$user.ics ; echo "$user -- OK" ; done
	echo "+-------------------------------------------------+OK"
	echo

	echo "Importando Listas de Distribuição..."
	echo
for user in `cat $DEST/listas/listas`; do zmprov cdl $user ; echo "$user -- OK" ; done
for list in `cat $DEST/listas/listas`
do
    for user in `grep -v '#' $DEST/listas/$list | grep '@'`
    do
        zmprov adlm $list $user
    done
done
	echo "+-------------------------------------------------+OK"
	echo
	
	echo "Importando Alias..."
	echo
for user in `cat $DEST/contas/usuarios`
do
    echo $user
    if [ -f "./$user.txt" ]; then
        for alias in `grep '@' ./$user.txt`
        do
            zmprov aaa $user $alias
            echo "$user -- OK";
        done
     fi
done
	echo "+-------------------------------------------------+OK"
	echo

	echo "Importando Assinaturas..."
	echo
for user in `cat $DEST/contas/usuarios`; do
zmprov csig $user "`cat $DEST/assinaturas/$user |grep zimbraSignatureName | sed -e 's/zimbraSignatureName: //'`" zimbraPrefMailSignatureHTML "`cat $DEST/assinaturas/$user |grep zimbraPrefMailSignatureHTML | sed -e 's/zimbraPrefMailSignatureHTML: //'`" ; 
	echo "$user -- OK";
done
	echo "+-------------------------------------------------+OK"
	echo

	echo "Importando Filtros..."
	echo
for user in `cat $DEST/contas/usuarios`; do
zmprov ma $user zimbraMailSieveScript "`cat $DEST/filtros/$user.filtros`"; 	echo "$user -- OK";
done
	echo "+-------------------------------------------------+OK"
	echo

	echo
	echo "Dados Importados"
    echo "Pressione qualquer tecla para continuar..."
    read msg
	Principal
} 
Principal

echo "[`date`] ==== Fim da rotina..."

#https://syslint.com/blog/tutorial/zimbra-server-migration-and-zimbra-account-transfer-the-perfect-method/
#https://blog.johannfenech.com/migrating-opensource-zimbra-8-6-0-on-centos-6-8-to-zimbra-8-7-1-on-centos-7-safely-and-with-no-downtime/
