#!/bin/bash
# Versao 2.3 em 07/10/2018
# Versao 3.0 em 26/06/2019
#######################################################

#+----------------GERANDO LOG-----------------------+OK"
SCRIPT=`basename $0`
LOG=`echo /opt/zimbra/$SCRIPT.log | sed s/'.sh'/'.log'/g`
exec &> >(tee -a "$LOG")
echo "[`date`] ==== Inicio de rotina..."
#+----------------GERANDO LOG-----------------------+OK"

clear
#Checa se o usuario é zimbra
LOCAL_USER=`id -u -n`

if [ $LOCAL_USER != "zimbra" ] ; then
	echo "     Rodar como usuario Zimbra"
	echo "     saindo..."
	echo ""
	exit
fi
Principal() {
   dir="Diretorio Atual		 : `pwd`"
	 hostname="Hostname			 : `hostname --fqdn`"
	 ip="IP						       : `ifconfig | awk 'NR>=2 && NR<=2' | awk '{print $3}'`"
   versaoso="Versao S.O.	 : `lsb_release -d | cut -d : -f 2- | sed 's/^[ \t]*//;s/[ \t]*$//'`"
	 release="Release			   : `lsb_release -r | cut -d : -f 2- | sed 's/^[ \t]*//;s/[ \t]*$//'`"
	 codename="Codename			 : `lsb_release -c | cut -d : -f 2- | sed 's/^[ \t]*//;s/[ \t]*$//'`"
	 kernel="Kernel			  	 : `uname -r`"
	 arquitetura="Arquitetura	   : `uname -m`"
	 versaozimbra="Versao Zimbra : `zmcontrol -v`"
   echo "+-------------------------------------------------+"
   echo "|           Utilitario para Zimbra                |"
   echo "+-------------------------------------------------+"
   echo "| Exportar / Importar Dados do Zimbra             |"
   echo "+-------------------------------------------------+"
   echo "| Escrito por:                                    |"
   echo "| Thiago Castro - www.hostlp.net                  |"
   echo "+-------------------------------------------------+"
   echo
   echo $dir
	 echo "+-------------------------------------------------+"
	 echo $hostname
	 echo "+-------------------------------------------------+"
	 echo $ip
	 echo "+-------------------------------------------------+"
	 echo $versaoso
	 echo "+-------------------------------------------------+"
	 echo $release
	 echo "+-------------------------------------------------+"
	 echo $codename
	 echo "+-------------------------------------------------+"
     echo $kernel
	 echo "+-------------------------------------------------+"
     echo $arquitetura
	 echo "+-------------------------------------------------+"
	 echo $versaozimbra
	 echo "+-------------------------------------------------+"
	 echo
   echo
   echo "Opcoes:"
   echo "1. Exportar COS e Contas"
	 echo "2. Exportar Alias e Listas"
	 echo "3. Exportar Agendas"
	 echo "4. Exportar Contatos"
	 echo "5. Exportar Filtros"
	 echo "6. Exportar Assinaturas"
	 echo
	 echo "7. Importar COS e Contas"
	 echo "8. Importar Alias e Listas"
	 echo "9. Importar Agendas"
	 echo "10. Importar Contatos"
	 echo "11. Importar Filtros"
	 echo "12. Importar Assinaturas"
	 echo
	 echo "13. Adicionar Tarefa Agendada"
	 echo
   echo "14. Sair"
	 echo
	 echo
   echo -n "Entre com a opcao desejada => "
   read opcao
   echo
   case $opcao in
    1) Exportar1 ;;
		2) Exportar2 ;;
		3) Exportar3 ;;
		4) Exportar4 ;;
		5) Exportar5 ;;
		6) Exportar6 ;;
    7) Importar1 ;;
		8) Importar2 ;;
		9) Importar3 ;;
		10) Importar4 ;;
		11) Importar5 ;;
		12) Importar6 ;;
		13) Tarefa ;;
    14) exit ;;
     *) "Opcao desconhecida." ; echo ; Principal ;;
     esac
}

Exportar1() {
	# Obter interface desejada e IP do Zimbra para conexão
	#IFACE="eth0"
	IP=`/sbin/ifconfig $IFACE | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p'`
	# Destino dos Arquivos
	echo -n "Onde salvar os backups..."
	read DESTB
	echo
	DEST="$DESTB/Zimbra/`hostname --fqdn`"
	DESTTEMP="/tmp"
	ZMPROV="/opt/zimbra/bin/zmprov"
	ZMMAILBOX="/opt/zimbra/bin/zmmailbox"

	# Diretorios
	if [ ! -d "$DEST/Contas" ]; then
	 mkdir $DEST/COS $DEST/Contas -p
	 echo "Criando diretórios COS e Contas"
	 else
	 echo "Diretorio COS/Contas já existentes em $DEST"
	 echo 
	 echo "Sobescrever? ENTER continua -- Ctr+C cancela"
	 read msg
	 #Principal
	fi

	# Definindo Variaveis de ambiente do Zimbra
	source ~/bin/zmshutil
	zmsetvars

	# Exportando Classes de Serviços
	echo "Exportando Classes de Serviços"
	ldapsearch -x -H ldap://$IP -D uid=zimbra,cn=admins,cn=zimbra -w $zimbra_ldap_password -b '' -LLL "(objectclass=zimbraCOS)" > $DEST/COS/cos.ldiff

	# Exportando Contas
	echo "Exportando Contas"
	ldapsearch -x -H ldap://$IP -D uid=zimbra,cn=admins,cn=zimbra -w $zimbra_ldap_password -b '' -LLL "(objectclass=zimbraAccount)" > $DEST/Contas/contas.ldiff
	echo
    echo "Pressione qualquer tecla para continuar..."
    read msg
    Principal
}
  
Exportar2() {
	# Obter interface desejada e IP do Zimbra para conexão
	#IFACE="eth0"
	IP=`/sbin/ifconfig $IFACE | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p'`
	# Destino dos Arquivos
	echo -n "Onde salvar os backups..."
	read DESTB
	echo
	DEST="$DESTB/Zimbra/`hostname --fqdn`"
	DESTTEMP="/tmp"
	ZMPROV="/opt/zimbra/bin/zmprov"
	ZMMAILBOX="/opt/zimbra/bin/zmmailbox"

	# Diretorios
	if [ ! -d "$DEST/Alias" ]; then
	 mkdir $DEST/Alias $DEST/Alias/alias $DEST/Listas -p
	 echo "Criando diretórios Alias, Listas"
	 else
	 echo "Diretorio Alias/Listas já existentes em $DEST"
	 echo 
	 echo "Sobescrever? ENTER continua -- Ctr+C cancela"
	 read msg
	 #Principal
	fi

	# Definindo Variaveis de ambiente do Zimbra
	source ~/bin/zmshutil
	zmsetvars
	
	# Exportando Alias
	echo "Exportando Alias"
	ldapsearch -x -H ldap://$IP -D uid=zimbra,cn=admins,cn=zimbra -w $zimbra_ldap_password  -b '' -LLL "(objectclass=zimbraAlias)" uid | grep ^uid | awk '{print $2}' > $DEST/Alias/alias.ldiff

	for MAIL in $(cat $DEST/Alias/alias.ldiff);
		do 
		  ldapsearch -x -H ldap://$IP -D uid=zimbra,cn=admins,cn=zimbra -w $zimbra_ldap_password -b '' -LLL "(&(uid=$MAIL)(objectclass=zimbraAlias))" > $DEST/Alias/alias/$MAIL.ldiff 
		cat $DEST/Alias/alias/*.ldiff > $DEST/Alias/apelidos.ldiff
	done 
	rm -rf $DEST/Alias/alias

	# Exportando Listas de Distribuição
	echo "Exportando Listas de Distribuição"
	ldapsearch -x -H ldap://$IP -D uid=zimbra,cn=admins,cn=zimbra -w $zimbra_ldap_password -b '' -LLL "(objectclass=zimbraDistributionList)" > $DEST/Listas/listas.ldiff
	echo
    echo "Pressione qualquer tecla para continuar..."
    read msg
    Principal
}

Exportar3() {
	# Obter interface desejada e IP do Zimbra para conexão
	#IFACE="eth0"
	IP=`/sbin/ifconfig $IFACE | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p'`
	# Destino dos Arquivos
	echo -n "Onde salvar os backups..."
	read DESTB
	echo
	DEST="$DESTB/Zimbra/`hostname --fqdn`"
	DESTTEMP="/tmp"
	ZMPROV="/opt/zimbra/bin/zmprov"
	ZMMAILBOX="/opt/zimbra/bin/zmmailbox"

	# Diretorios
	if [ ! -d "$DEST/Agendas" ]; then
	 mkdir $DEST/Agendas -p
	 echo "Criando diretório Agendas"
	 else
	 echo "Diretorio Agendas já existente em $DEST"
	 echo 
	 echo "Sobescrever? ENTER continua -- Ctr+C cancela"
	 read msg
	 #Principal
	fi

	# Definindo Variaveis de ambiente do Zimbra
	source ~/bin/zmshutil
	zmsetvars
	
	# Exportando Agendas
	echo "Exportando Agendas"
	cd $DEST/Agendas/
	for MAIL in $($ZMPROV -l gaa | sort); 	do
		$ZMMAILBOX  -z -m $MAIL getRestURL "/calendar?fmt=ics" > $DEST/Agendas/$MAIL.ics
    done
	echo
    echo "Pressione qualquer tecla para continuar..."
    read msg
    Principal
}

Exportar4() {
	# Obter interface desejada e IP do Zimbra para conexão
	#IFACE="eth0"
	IP=`/sbin/ifconfig $IFACE | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p'`
	# Destino dos Arquivos
	echo -n "Onde salvar os backups..."
	read DESTB
	echo
	DEST="$DESTB/Zimbra/`hostname --fqdn`"
	DESTTEMP="/tmp"
	ZMPROV="/opt/zimbra/bin/zmprov"
	ZMMAILBOX="/opt/zimbra/bin/zmmailbox"
	
	# Diretorios
	if [ ! -d "$DEST/Contatos" ]; then
	 mkdir $DEST/Contatos -p
	 echo "Criando diretório Contatos"
	 else
	 echo "Diretorio Contatos já existente em $DEST"
	 echo 
	 echo "Sobescrever? ENTER continua -- Ctr+C cancela"
	 read msg
	 #Principal
	fi

	# Definindo Variaveis de ambiente do Zimbra
	source ~/bin/zmshutil
	zmsetvars
	
	# Exportando Contatos
	echo "Exportando Contatos"
	cd $DEST/Contatos/
	for MAIL in $($ZMPROV -l gaa | sort); 	do
		$ZMMAILBOX  -z -m $MAIL getRestURL "/contacts?fmt=csv" > $DEST/Contatos/$MAIL.csv
    done
	
	echo
    echo "Pressione qualquer tecla para continuar..."
    read msg
    Principal
}

Exportar5() {
	# Obter interface desejada e IP do Zimbra para conexão
	#IFACE="eth0"
	IP=`/sbin/ifconfig $IFACE | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p'`
	# Destino dos Arquivos
	echo -n "Onde salvar os backups..."
	read DESTB
	echo
	DEST="$DESTB/Zimbra/`hostname --fqdn`"
	DESTTEMP="/tmp"
	ZMPROV="/opt/zimbra/bin/zmprov"
	ZMMAILBOX="/opt/zimbra/bin/zmmailbox"

	# Diretorios
	if [ ! -d "$DEST/Filtros" ]; then
	 mkdir $DEST/Filtros -p
	 echo "Criando diretório Filtros"
	 else
	 echo "Diretorio Filtros já existente em $DEST"
	 echo 
	 echo "Sobescrever? ENTER continua -- Ctr+C cancela"
	 read msg
	 #Principal
	fi
	
	# Exportando Filtros
	echo "Exportando Filtros"
	USERS=`zmprov -l gaa | sort`;
	for ACCOUNT in $USERS; do
	NAME=`echo $ACCOUNT`;
	done
	filter=`zmprov ga $NAME zimbraMailSieveScript > $DESTTEMP/$NAME`
	sed -i -e "1d" $DESTTEMP/$NAME
	sed 's/zimbraMailSieveScript: //g' $DESTTEMP/$NAME > $DEST/Filtros/$NAME
	rm $DESTTEMP/$NAME
	echo
    echo "Pressione qualquer tecla para continuar..."
    read msg
    Principal
}

Exportar6() {
	# Obter interface desejada e IP do Zimbra para conexão
	#IFACE="eth0"
	IP=`/sbin/ifconfig $IFACE | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p'`
	# Destino dos Arquivos
	echo -n "Onde salvar os backups..."
	read DESTB
	echo
	DEST="$DESTB/Zimbra/`hostname --fqdn`"
	DESTTEMP="/tmp"
	ZMPROV="/opt/zimbra/bin/zmprov"
	ZMMAILBOX="/opt/zimbra/bin/zmmailbox"

	# Diretorios
	if [ ! -d "$DEST/Assinaturas" ]; then
	 mkdir $DEST/Assinaturas -p
	 echo "Criando diretório Assinaturas"
	 else
	 echo "Diretorio Assinaturas já existente em $DEST"
	 echo 
	 echo "Sobescrever? ENTER continua -- Ctr+C cancela"
	 read msg
	 #Principal
	fi
	
	# Exportando Assinaturas
	echo "Exportando Assinaturas"
	USERS=`zmprov -l gaa | sort`;
	for ACCOUNT in $USERS; do
	NAME=`echo $ACCOUNT`;
	done
	filter=`zmprov ga $NAME zimbraPrefMailSignature > $DESTTEMP/$NAME`
	sed -i -e "1d" $DESTTEMP/$NAME
	sed 's/zimbraPrefMailSignature: //g' $DESTTEMP/$NAME > $DEST/Assinaturas/$NAME
	rm $DESTTEMP/$NAME
	echo
    echo "Pressione qualquer tecla para continuar..."
    read msg
    Principal
}

Importar1() {
	# Obter interface desejada e IP do Zimbra para conexão
	IFACE="eth0"
	IP=`/sbin/ifconfig $IFACE | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p'`
	# Destino dos Arquivos
	echo -n "Onde recuperar os backups..."
	read DESTB
	echo
	DEST="$DESTB/Zimbra/`hostname --fqdn`"
	DESTTEMP="/tmp"
	ZMPROV="/opt/zimbra/bin/zmprov"
	ZMMAILBOX="/opt/zimbra/bin/zmmailbox"

	# Definindo Variaveis de ambiente do Zimbra
	source ~/bin/zmshutil
	zmsetvars

	# Importando Classes de Serviços
	echo "Importando Classes de Serviços"
	ldapadd -c -x -H ldap://$IP -D uid=zimbra,cn=admins,cn=zimbra -w $zimbra_ldap_password -f $DEST/COS/cos.ldiff

	# Importando Contas
	echo "Importando Contas"
	ldapadd -c -x -H ldap://$IP -D uid=zimbra,cn=admins,cn=zimbra -w $zimbra_ldap_password -f $DEST/Contas/contas.ldiff
	echo
    echo "Pressione qualquer tecla para continuar..."
    read msg
    Principal
}
  
Importar2() {
	# Obter interface desejada e IP do Zimbra para conexão
	IFACE="eth0"
	IP=`/sbin/ifconfig $IFACE | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p'`
	# Destino dos Arquivos
	echo -n "Onde recuperar os backups..."
	read DESTB
	echo
	DEST="$DESTB/Zimbra/`hostname --fqdn`"
	DESTTEMP="/tmp"
	ZMPROV="/opt/zimbra/bin/zmprov"
	ZMMAILBOX="/opt/zimbra/bin/zmmailbox"

	# Definindo Variaveis de ambiente do Zimbra
	source ~/bin/zmshutil
	zmsetvars
	
	# Importando Alias
	echo "Importando Alias"
	ldapadd -c -x -H ldap://$IP -D uid=zimbra,cn=admins,cn=zimbra -w $zimbra_ldap_password -f $DEST/Alias/apelidos.ldiff

	# Importando Listas de Distribuição
	echo "Importando Listas de Distribuição"
	ldapadd -c -x -H ldap://$IP -D uid=zimbra,cn=admins,cn=zimbra -w $zimbra_ldap_password -f $DEST/Listas/listas.ldiff
	echo
    echo "Pressione qualquer tecla para continuar..."
    read msg
    Principal
}	

Importar3() {
	# Obter interface desejada e IP do Zimbra para conexão
	IFACE="eth0"
	IP=`/sbin/ifconfig $IFACE | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p'`
	# Destino dos Arquivos
	echo -n "Onde recuperar os backups..."
	read DESTB
	echo
	DEST="$DESTB/Zimbra/`hostname --fqdn`"
	DESTTEMP="/tmp"
	ZMPROV="/opt/zimbra/bin/zmprov"
	ZMMAILBOX="/opt/zimbra/bin/zmmailbox"

	# Definindo Variaveis de ambiente do Zimbra
	source ~/bin/zmshutil
	zmsetvars
	
	# Importando Agendas
	echo "Importando Agendas"
	cd $DEST/Agendas/
	find . -type f -size -95c -exec rm -f {} \;
	for CONTA in $(ls |awk -F ".ics" '{print $1}') ; do zmmailbox -z -m $CONTA pru /Calendar $DEST/Agendas/$CONTA.ics ;done
	echo
    echo "Pressione qualquer tecla para continuar..."
    read msg
    Principal
}

Importar4() {
	# Obter interface desejada e IP do Zimbra para conexão
	IFACE="eth0"
	IP=`/sbin/ifconfig $IFACE | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p'`
	# Destino dos Arquivos
	echo -n "Onde recuperar os backups..."
	read DESTB
	echo
	DEST="$DESTB/Zimbra/`hostname --fqdn`"
	DESTTEMP="/tmp"
	ZMPROV="/opt/zimbra/bin/zmprov"
	ZMMAILBOX="/opt/zimbra/bin/zmmailbox"

	# Definindo Variaveis de ambiente do Zimbra
	source ~/bin/zmshutil
	zmsetvars
	
	# Importando Contatos
	echo "Importando Contatos"
	cd $DEST/Contatos/
	for CONTA in $(ls |awk -F ".csv" '{print $1}') ; do zmmailbox -z -m $CONTA pru /Contacts $DEST/Contatos/$CONTA.csv ;done
	echo
    echo "Pressione qualquer tecla para continuar..."
    read msg
    Principal
}

Importar5() {
	# Obter interface desejada e IP do Zimbra para conexão
	IFACE="eth0"
	IP=`/sbin/ifconfig $IFACE | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p'`
	# Destino dos Arquivos
	echo -n "Onde recuperar os backups..."
	read DESTB
	echo
	DEST="$DESTB/Zimbra/`hostname --fqdn`"
	DESTTEMP="/tmp"
	ZMPROV="/opt/zimbra/bin/zmprov"
	ZMMAILBOX="/opt/zimbra/bin/zmmailbox"

	# Definindo Variaveis de ambiente do Zimbra
	source ~/bin/zmshutil
	zmsetvars
	
	# Importando Filtros
	echo "Importando Filtros"
	for file in $DEST/Filtros/*
		do
	StrFilter=`cat "$file"`
	Acc=`echo $file | cut -d "/" -f5`
		done
	USERS=`zmprov -l gaa | sort`;
	for ACCOUNT in $USERS; do
	NAME=`echo $ACCOUNT`;
	zmprov ma $NAME zimbraMailSieveScript '$StrFilter'
		done
	echo
    echo "Pressione qualquer tecla para continuar..."
    read msg
    Principal
}

Importar6() {
	# Obter interface desejada e IP do Zimbra para conexão
	IFACE="eth0"
	IP=`/sbin/ifconfig $IFACE | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p'`
	# Destino dos Arquivos
	echo -n "Onde recuperar os backups..."
	read DESTB
	echo
	DEST="$DESTB/Zimbra/`hostname --fqdn`"
	DESTTEMP="/tmp"
	ZMPROV="/opt/zimbra/bin/zmprov"
	ZMMAILBOX="/opt/zimbra/bin/zmmailbox"

	# Definindo Variaveis de ambiente do Zimbra
	source ~/bin/zmshutil
	zmsetvars
	
	# Importando Assinaturas
	echo "Importando Assinaturas"
	for file in $DEST/Assinaturas/*
		do
	StrSign=`cat "$file"`
	Acc=`echo $file | cut -d "/" -f5`
		done
	zmprov ma $Acc zimbraPrefMailSignature '$StrSign'
	echo
    echo "Pressione qualquer tecla para continuar..."
    read msg
    Principal
}

 Tarefa() {
	# Adicionar Tarefa
	echo "Adicionando terafa agendada para todos os dias 00:00hrs"
	#echo "00 00 * * *"  zimbra  /opt/zimbra/Export_Import_Dados_Zimbra > /etc/cron.d/export_dados_zimbra
	echo
    echo "Pressione qualquer tecla para continuar..."
    read msg
	Principal
} 
Principal

echo "[`date`] ==== Fim de rotina..."
