#!/bin/bash

#+----------------GERANDO LOG-----------------------+OK"
SCRIPT=`basename $0`
LOG=`echo $DEST/$SCRIPT.log | sed s/'.sh'/'.log'/g`
exec &> >(tee -a "$LOG") 1&> /dev/null
echo "[`date`] ==== Inicio de rotina..."
#+----------------GERANDO LOG-----------------------+OK"

cd /tmp/
clear

#Checa se o usuario é zimbra
LOCAL_USER=`id -u -n`

if [ $LOCAL_USER != "zimbra" ] ; then
	echo "     Rodar como usuario Zimbra"
	echo "     saindo..."
	echo ""
	exit
fi

	clear
     dir="Diretorio Atual		 : `pwd`"
	 hostname="Hostname			 : `hostname --fqdn`"
	 ip="IP						 : `ifconfig | awk 'NR>=2 && NR<=2' | awk '{print $3}'`"
     versaoso="Versao S.O.		 : `lsb_release -d | cut -d : -f 2- | sed 's/^[ \t]*//;s/[ \t]*$//'`"
	 release="Release			 : `lsb_release -r | cut -d : -f 2- | sed 's/^[ \t]*//;s/[ \t]*$//'`"
	 codename="Codename			 : `lsb_release -c | cut -d : -f 2- | sed 's/^[ \t]*//;s/[ \t]*$//'`"
	 kernel="Kernel				 : `uname -r`"
	 arquitetura="Arquitetura	 : `uname -m`"
	 versaozimbra="Versao Zimbra : `/opt/zimbra/bin/zmcontrol -v`"
	 echo
     echo "+-------------------------------------------------+"
     echo "|           Utilitario para Zimbra                |"
     echo "+-------------------------------------------------+"
     echo "| Exportar / Importar Contas do Zimbra    v1.6    |"
     echo "+-------------------------------------------------+"
     echo "| Escrito por:                                    |"
     echo "| Thiago Castro - www.hostlp.net                  |"
     echo "+-------------------------------------------------+"
     echo
     echo $dir
	 echo "+-------------------------------------------------+"
	 echo $hostname
	 echo "+-------------------------------------------------+"
	 echo $ip
	 echo "+-------------------------------------------------+"
	 echo $versaoso
	 echo "+-------------------------------------------------+"
	 echo $release
	 echo "+-------------------------------------------------+"
	 echo $codename
	 echo "+-------------------------------------------------+"
     echo $kernel
	 echo "+-------------------------------------------------+"
     echo $arquitetura
	 echo "+-------------------------------------------------+"
	 echo $versaozimbra
	 echo "+-------------------------------------------------+"
	 echo
     sleep 5
	 echo
	 echo "==================EXECUTANDO======================="
	 echo


# Obtemos uma lista de todas as contas do servidor
#	source ~/bin/zmshutil
	source /opt/zimbra/bin/zmshutil
	zmsetvars
	zmprov=/opt/zimbra/bin/zmprov
	zmmailbox=/opt/zimbra/bin/zmmailbox
	ldapsearch=/opt/zimbra/common/bin/ldapsearch
	DOMAIN=`hostname`
	DEST="/opt/zimbra/backup/$DOMAIN"
	cp -rf $DEST /tmp/$DOMAIN-BKP-$(date "+%Y%m%d")
	mkdir $DEST/cos $DEST/dominio $DEST/contas $DEST/contatos $DEST/agendas $DEST/listas $DEST/alias $DEST/assinaturas $DEST/filtros -p
	chown zimbra:zimbra $DEST -R
	clear
	
#######################################################

	echo "Exportando COS..."
	echo
	$zmprov gac | tee -a $DEST/cos/cos
	$ldapsearch -x -H $ldap_master_url -D $zimbra_ldap_userdn -w $zimbra_ldap_password -b '' -LLL "(objectclass=zimbraCOS)" > $DEST/cos/cos.ldiff
	echo "+-------------------------------------------------+OK"
	echo

	echo "Exportando Dominios..."
	echo
	rm -rf $DEST/dominio/dominio
$zmprov gad | tee -a $DEST/dominio/dominio
	echo "+-------------------------------------------------+OK"
	echo
	
	echo "Exportando Contas..."
	echo
	rm -rf $DEST/contas/*
	/opt/zimbra/bin/zmhostname > $DEST/server_old
$zmprov gaaa | tee -a $DEST/contas/admins
$zmprov -l gaa | tee -a $DEST/contas/usuarios
for user in `cat $DEST/contas/usuarios`; do $ldapsearch -x -H $ldap_master_url -D $zimbra_ldap_userdn -w $zimbra_ldap_password -b '' -LLL "(zimbraMailDeliveryAddress=$user)" > $DEST/contas/$user.ldiff ; done
	echo "+-------------------------------------------------+OK"
	echo

	echo "Exportando Contatos..."
	echo
$zmprov -l gaa | while read conta; do $zmmailbox -z -m $conta gru /Contacts > $DEST/contatos/$conta.csv ;
	echo "$conta" ;
done	
	echo "+-------------------------------------------------+OK"
	echo

	echo "Exportando Agendas..."
	echo
	cd $DEST/agendas
for user in $($zmprov -l gaa | sort); do
        $zmmailbox  -z -m $user getRestURL "/calendar?fmt=ics" > $DEST/agendas/$user.ics ;
	echo "$user" ;
done
	echo "+-------------------------------------------------+OK"
	echo
	
	echo "Exportando Listas de Distribuição..."
	echo
$zmprov gadl | tee -a $DEST/listas/listas
for lists in `cat $DEST/listas/listas`; do $zmprov gdlm $lists > $DEST/listas/$lists ; done
	echo "+-------------------------------------------------+OK"
	echo

	echo "Exportando Alias..."
	echo
for user in `cat $DEST/contas/usuarios`; do $zmprov ga $user | grep zimbraMailAlias | awk '{print $2}' | tee -a $DEST/alias/$user ; done
find $DEST/alias/. -type f -empty | xargs -n1 rm -v 1&> /dev/null
	echo "+-------------------------------------------------+OK"
	echo

	echo "Exportando Assinaturas..."
	echo
for user in `cat $DEST/contas/usuarios`; do
$zmprov ga $user zimbraPrefMailSignatureHTML > /tmp/assinatura;
	sed -i -e "1d" /tmp/assinatura ;
	sed 's/zimbraPrefMailSignatureHTML: //g' /tmp/assinatura > $DEST/assinaturas/$user.assinatura ;
	rm -rf /tmp/assinatura;
	`$zmprov ga $user zimbraSignatureName > /tmp/name` ;
	sed -i -e "1d" /tmp/name ;
	sed 's/zimbraSignatureName: //g' /tmp/name > $DEST/assinaturas/$user.name ;
	rm -rf /tmp/name ;
	echo "$user";
done
	echo "+-------------------------------------------------+OK"
	echo

	echo "Exportando Filtros..."
	echo
for user in `cat $DEST/contas/usuarios`; do
$zmprov ga $user zimbraMailSieveScript > /tmp/filtros
    sed -i -e "1d" /tmp/filtros
    sed 's/zimbraMailSieveScript: //g' /tmp/filtros  > $DEST/filtros/$user.filtros
    rm -f /tmp/filtros
    echo "$user"
done 
	echo "+-------------------------------------------------+OK"
	echo
	
	chown zimbra:zimbra $DEST -R
	echo "Dados Exportadas"
 
echo "[`date`] ==== Fim da rotina..."

