#!/bin/bash

#+----------------GERANDO LOG-----------------------+OK"
SCRIPT=`basename $0`
LOG=`echo $DEST/$SCRIPT.log | sed s/'.sh'/'.log'/g`
exec &> >(tee -a "$LOG")
echo "[`date`] ==== Inicio de rotina..."
#+----------------GERANDO LOG-----------------------+OK"

cd /tmp/
clear

#Checa se o usuario é zimbra
LOCAL_USER=`id -u -n`

if [ $LOCAL_USER != "zimbra" ] ; then
	echo "     Rodar como usuario Zimbra"
	echo "     saindo..."
	echo ""
	exit
fi
Principal() {
	clear
     dir="Diretorio Atual		 : `pwd`"
	 hostname="Hostname			 : `hostname --fqdn`"
	 ip="IP						 : `ifconfig | awk 'NR>=2 && NR<=2' | awk '{print $3}'`"
     versaoso="Versao S.O.		 : `lsb_release -d | cut -d : -f 2- | sed 's/^[ \t]*//;s/[ \t]*$//'`"
	 release="Release			 : `lsb_release -r | cut -d : -f 2- | sed 's/^[ \t]*//;s/[ \t]*$//'`"
	 codename="Codename			 : `lsb_release -c | cut -d : -f 2- | sed 's/^[ \t]*//;s/[ \t]*$//'`"
	 kernel="Kernel				 : `uname -r`"
	 arquitetura="Arquitetura	 : `uname -m`"
	 versaozimbra="Versao Zimbra : `/opt/zimbra/bin/zmcontrol -v`"
     echo "+-------------------------------------------------+"
     echo "|           Utilitario para Zimbra                |"
     echo "+-------------------------------------------------+"
     echo "| Exportar / Importar Contas do Zimbra    v1.5    |"
     echo "+-------------------------------------------------+"
     echo "| Escrito por:                                    |"
     echo "| Thiago Castro - www.hostlp.net                  |"
     echo "+-------------------------------------------------+"
     echo
     echo $dir
	 echo "+-------------------------------------------------+"
	 echo $hostname
	 echo "+-------------------------------------------------+"
	 echo $ip
	 echo "+-------------------------------------------------+"
	 echo $versaoso
	 echo "+-------------------------------------------------+"
	 echo $release
	 echo "+-------------------------------------------------+"
	 echo $codename
	 echo "+-------------------------------------------------+"
     echo $kernel
	 echo "+-------------------------------------------------+"
     echo $arquitetura
	 echo "+-------------------------------------------------+"
	 echo $versaozimbra
	 echo "+-------------------------------------------------+"
	 echo
     echo
     echo "Opcoes:"
     echo "1. Exportar COS, Dominios, Contas, Contatos, Agendas, Listas, Alias, Assinaturas e Filtros"
	 echo
	 echo "2. Importar COS, Dominios, Contas, Contatos, Agendas, Listas, Alias, Assinaturas e Filtros"
	 echo
     echo "3. Sair"
	 echo
	 echo
     echo -n "Entre com a opcao desejada => "
     read opcao
     echo
     case $opcao in
        1) Exportar1 ;;
        2) Importar1 ;;
        3) exit ;;
        *) "Opcao desconhecida." ; echo ; Principal ;;
     esac
}

Exportar1() {
# Obtemos uma lista de todas as contas do servidor
	source ~/bin/zmshutil
	zmsetvars
	echo "Exportar todo os dados de um dominio"
	echo -n "Digite dominio completo...: "
	read DOMAIN
	echo
	DEST="zimbra/$DOMAIN"
	cp -rf $DEST zimbra/$DOMAIN-BKP-$(date "+%Y%m%d")
	mkdir $DEST/cos $DEST/dominio $DEST/contas $DEST/contatos $DEST/listas $DEST/alias $DEST/assinaturas $DEST/filtros -p
	chown zimbra:zimbra $DEST -R
	clear
	
#######################################################

	echo "Exportando COS..."
	echo
	echo "Exportar COS? - Sim/Nao"
	read CONFIRMA
	case $CONFIRMA in
s|S|Sim|sim)
	ldapsearch -x -H $ldap_master_url -D $zimbra_ldap_userdn -w $zimbra_ldap_password -b '' -LLL "(objectclass=zimbraCOS)" > $DEST/cos/cos.ldiff
		;;
n|N|Nao|nao)
		;;
*) echo  "Opcao Invalida" ;; esac
	echo "+-------------------------------------------------+OK"
	echo
	
	echo "Exportando Dominio..."
	echo
	rm -rf $DEST/dominio/dominio
	zmprov gad | grep "$DOMAIN" | tee -a $DEST/dominio/dominio
	echo "+-------------------------------------------------+OK"
	echo
	
	echo "Exportando Contas..."
	echo
	rm -rf $DEST/contas/*
	zmhostname > $DEST/server_old
	zmprov gaaa | grep "$DOMAIN" | tee -a $DEST/contas/admins
	zmprov -l gaa | grep "$DOMAIN" | tee -a $DEST/contas/usuarios
for user in `cat $DEST/contas/usuarios`; do ldapsearch -x -H $ldap_master_url -D $zimbra_ldap_userdn -w $zimbra_ldap_password -b '' -LLL "(zimbraMailDeliveryAddress=$user)" > $DEST/contas/$user.ldiff ; done
	echo "+-------------------------------------------------+OK"
	echo

	echo "Exportando os dados das Contas..."
	echo
	echo "Exportar dados de caixa postal? - Sim/Nao"
	read CONFIRMA
	case $CONFIRMA in
s|S|Sim|sim)
for user in `cat $DEST/contas/usuarios`; do zmmailbox -z -m $user getRestURL '/?fmt=tgz' > $DEST/contas/$user.tgz ;  echo $user ; done
		;;
n|N|Nao|nao)
		;;
*) echo  "Opcao Invalida" ;; esac
	echo "+-------------------------------------------------+OK"
	echo
	
	echo "Exportando Contatos..."
	echo
zmprov -l gaa "$DOMAIN" | while read conta; do zmmailbox -z -m $conta gru /Contacts > $DEST/contatos/$conta.csv; echo "$conta"; done	
	echo "+-------------------------------------------------+OK"
	echo

	echo "Exportando Agendas..."
	echo
	cd $DEST/agendas
for user in $($zmprov -l gaa | sort); do
        $zmmailbox  -z -m $user getRestURL "/calendar?fmt=ics" > $DEST/agendas/$user.ics
done
	echo "+-------------------------------------------------+OK"
	echo
	
	echo "Exportando Listas de Distribuição..."
	echo
zmprov gadl "$DOMAIN" | tee -a $DEST/listas/listas
for lists in `cat $DEST/listas/listas`; do zmprov gdlm $lists > $DEST/listas/$lists ; done
	echo "+-------------------------------------------------+OK"
	echo

	echo "Exportando Alias..."
	echo
for user in `cat $DEST/contas/usuarios`; do zmprov ga $user | grep zimbraMailAlias | awk '{print $2}' | tee -a $DEST/alias/$user ; done
find $DEST/alias/. -type f -empty | xargs -n1 rm -v 1&> /dev/null
	echo "+-------------------------------------------------+OK"
	echo

	echo "Exportando Assinaturas..."
	echo
for user in `cat $DEST/contas/usuarios`; do
	zmprov ga $user zimbraPrefMailSignatureHTML > /tmp/assinatura;
	sed -i -e "1d" /tmp/assinatura ;
	sed 's/zimbraPrefMailSignatureHTML: //g' /tmp/assinatura > $DEST/assinaturas/$user.assinatura ;
	rm -rf /tmp/assinatura;
	`zmprov ga $user zimbraSignatureName > /tmp/name` ;
	sed -i -e "1d" /tmp/name ;
	sed 's/zimbraSignatureName: //g' /tmp/name > $DEST/assinaturas/$user.name ;
	rm -rf /tmp/name ;
	echo "$user";
done
	echo "+-------------------------------------------------+OK"

	echo "Exportando Filtros..."
	echo
for user in `cat $DEST/contas/usuarios`; do
    zmprov ga $user zimbraMailSieveScript > /tmp/filtros
    sed -i -e "1d" /tmp/filtros
    sed 's/zimbraMailSieveScript: //g' /tmp/filtros  > $DEST/filtros/$user.filtros
    rm -f /tmp/filtros
    echo "$user"
done 
	echo "+-------------------------------------------------+OK"
	
	echo
	chown zimbra:zimbra $DEST -R
	echo "Dados Exportadas"
    echo "Pressione qualquer tecla para continuar..."
    read msg
    Principal
}

Importar1() {
# já com todos os dados no novo servidor servidor
	source ~/bin/zmshutil
	zmsetvars
	echo "Importar todo os dados de um dominio"
	echo -n "Digite dominio completo...: "
	read DOMAIN
	echo
	cd /tmp/
	DEST="zimbra/$DOMAIN"
#	mkdir $DEST/cos $DEST/dominio $DEST/contas $DEST/contatos $DEST/listas $DEST/alias -p
	chown zimbra:zimbra $DEST -R
	clear
	
#######################################################

	echo "Importando COS..."
	echo
	echo "Importar COS? - Sim/Nao"
	read CONFIRMA
	case $CONFIRMA in
s|S|Sim|sim)
	ldapadd -c -x -H $ldap_master_url -D $zimbra_ldap_userdn -w $zimbra_ldap_password -f $DEST/cos/cos.ldiff
		;;
n|N|Nao|nao)
		;;
*) echo  "Opcao Invalida" ;; esac
	echo "+-------------------------------------------------+OK"
	echo

	echo "Importando Dominios..."
	echo
for domain in `cat $DEST/dominio/dominio`; do zmprov cd $domain zimbraAuthMech zimbra ;echo $domain ;done
	echo "+-------------------------------------------------+OK"
	echo

	echo "Retirando da importação contas spam, ham, virus e galsync..."
	echo
find $DEST -type f -name '*' -exec sed -i '/spam/d' "{}" \;
find $DEST -type f -name '*' -exec sed -i '/ham/d' "{}" \;
find $DEST -type f -name '*' -exec sed -i '/virus/d' "{}" \;
find $DEST -type f -name '*' -exec sed -i '/gal/d' "{}" \;
find $DEST -type f -name '*' -exec sed -i '/admin/d' "{}" \;
find $DEST -name 'spam.*' -exec rm {} \;
find $DEST -name 'ham.*' -exec rm {} \;
find $DEST -name 'virus.*' -exec rm {} \;
find $DEST -name 'gal.*' -exec rm {} \;
find $DEST -name 'admin.*' -exec rm {} \;
	echo "+-------------------------------------------------+OK"
	echo

	echo "Importando Contas..."
	echo
#	echo -n "Digite o nome do Servidor antigo...: "
#	read SERVEROLD
#	echo -n "Digite o nome do Servidor novo.....: "
#	read SERVENEW
	SERVEROL="cat $DEST/server_old"
	SERVERNE="`zmhostname`"
	find $DEST -type f -name '*.ldiff' -exec sed -i 's/$SERVEROL/$SERVERNE/g' "{}" \;
for user in `cat $DEST/contas/usuarios`; do ldapadd -x -H $ldap_master_url -D $zimbra_ldap_userdn -c -w $zimbra_ldap_password -f $DEST/contas/$user.ldiff ; done
	echo "+-------------------------------------------------+OK"
	echo

	echo "Importando os dados das Contas..."
	echo
	echo "Importar dados de caixa postal? - Sim/Nao"
	read CONFIRMA
	case $CONFIRMA in
s|S|Sim|sim)
for user in `cat $DEST/contas/usuarios`; do zmmailbox -z -m $user postRestURL "/?fmt=tgz&resolve=skip" $DEST/contas/$user.tgz ;  echo "$user -- OK "; done
		;;
n|N|Nao|nao)
		;;
*) echo  "Opcao Invalida" ;; esac
	echo "+-------------------------------------------------+OK"
	echo
	
	echo "Importando Contatos..."
	echo
for conta in $(ls $DEST/contatos |awk -F ".csv" '{print $1}') ; do zmmailbox -z -m $conta pru /Contacts $DEST/contatos/$conta.csv ;done
#zmprov -l gaa "$DOMAIN" | while read conta; do zmmailbox -z -m $conta pru /Contacts $DEST/contatos/$conta.csv ; done
	echo "+-------------------------------------------------+OK"
	echo

	echo "Importando Agendas..."
	echo
	cd $DEST/agendas
	find . -type f -size -95c -exec rm -f {} \;
	for user in $(ls |awk -F ".ics" '{print $1}') ; do zmmailbox -z -m $user pru /Calendar $DEST/agendas/$user.ics ;done
	echo "+-------------------------------------------------+OK"
	echo

	echo "Importando Listas de Distribuição..."
	echo
for lists in `cat $DEST/listas/listas`; do zmprov cdl $lists ; echo "$lists -- OK " ; done
	echo "+-------------------------------------------------+OK"
	echo
	
	echo "Importando Alias..."
	echo
for user in `cat $DEST/contas/usuarios`
do
    echo $user
    if [ -f "./$user.txt" ]; then
        for alias in `grep '@' ./$user.txt`
        do
            zmprov aaa $user $alias
            echo "$user ALIAS $alias - OK"
        done
     fi
done
	echo "+-------------------------------------------------+OK"
	echo

	echo "Importando Assinaturas..."
	echo
for user in `cat $DEST/contas/usuarios`; do
	zmprov ma $user zimbraSignatureName "`cat $DEST/assinaturas/$user.name`";
	zmprov ma $user zimbraPrefMailSignatureHTML "`cat $DEST/assinaturas/$user.assinatura`";
	zmprov ga $user zimbraSignatureId > /tmp/firmaid; sed -i -e "1d" /tmp/firmaid;
	firmaid=`sed 's/zimbraSignatureId: //g' /tmp/firmaid`;
	zmprov ma $user zimbraPrefDefaultSignatureId "$firmaid";
	zmprov ma $user zimbraPrefForwardReplySignatureId "$firmaid";
	rm -rf /tmp/firmaid;
	echo "$user -- OK";
done
	echo "+-------------------------------------------------+OK"
	echo

	echo "Importando Filtros..."
	echo
for user in `cat $DEST/contas/usuarios`; do
    zmprov ma $user zimbraMailSieveScript "`cat $DEST/filtros/$user.filtros`";
	echo "$user -- OK";
done
	echo "+-------------------------------------------------+OK"
	echo

	echo
	echo "Dados Importados"
    echo "Pressione qualquer tecla para continuar..."
    read msg
	Principal
} 
Principal

echo "[`date`] ==== Fim de rotina..."

#https://syslint.com/blog/tutorial/zimbra-server-migration-and-zimbra-account-transfer-the-perfect-method/
#https://blog.johannfenech.com/migrating-opensource-zimbra-8-6-0-on-centos-6-8-to-zimbra-8-7-1-on-centos-7-safely-and-with-no-downtime/
