#!/bin/bash
clear

#Checa se o usuario é root
LOCAL_USER=`id -u -n`

if [ $LOCAL_USER != "root" ] ; then
	echo "     Rodar como usuario root"
	echo "     saindo..."
	echo ""
	exit
fi
	dir="Diretorio Atual		 : `pwd`"
	hostname="Hostname			 : `hostname --fqdn`"
	ip="IP						 : `ifconfig | awk 'NR>=2 && NR<=2' | awk '{print $3}'`"
    versaoso="Versao S.O.		 : `lsb_release -d | cut -d : -f 2- | sed 's/^[ \t]*//;s/[ \t]*$//'`"
	release="Release			 : `lsb_release -r | cut -d : -f 2- | sed 's/^[ \t]*//;s/[ \t]*$//'`"
	codename="Codename			 : `lsb_release -c | cut -d : -f 2- | sed 's/^[ \t]*//;s/[ \t]*$//'`"
	kernel="Kernel				 : `uname -r`"
	arquitetura="Arquitetura	 : `uname -m`"
	versaozimbra="Versao Zimbra : `su - zimbra -c 'zmcontrol -v'`"
    echo "+-------------------------------------------------+"
    echo "|           Utilitario para Zimbra   1.3          |"
    echo "+-------------------------------------------------+"
    echo "+-------------------------------------------------+"
    echo "| Escrito por:                                    |"
    echo "| Thiago Castro - www.hostlp.cloud                |"
    echo "+-------------------------------------------------+"
    echo
    echo $dir
	echo "+-------------------------------------------------+"
	echo $hostname
	echo "+-------------------------------------------------+"
	echo $ip
	echo "+-------------------------------------------------+"
	echo $versaoso
	echo "+-------------------------------------------------+"
	echo $release
	echo "+-------------------------------------------------+"
	echo $codename
	echo "+-------------------------------------------------+"
    echo $kernel
	echo "+-------------------------------------------------+"
    echo $arquitetura
	echo "+-------------------------------------------------+"
	echo $versaozimbra
	echo "+-------------------------------------------------+"
	echo
	echo "Aperte <ENTER> para continuar e começar..."
	read 
	sleep 5
	echo
	echo "==================EXECUTANDO======================="
	echo
	
#Variavel
UsrZ="su - zimbra -c"

#Abrindo porta 80
echo "Abrindo Porta 80..."
iptables -A INPUT -p tcp -m tcp --dport 80 -j ACCEPT
	 echo "+-------------------------------------------------+OK"

echo "Deseja instalar LetsEncrypt? - Sim/Nao"
read CONFIRMA
case $CONFIRMA in
s|S|Sim|sim) 
#Baixa/Atualiza o LetsEncrypt
echo "Baixa/Atualiza o LetsEncrypt..."
cd 
sudo apt install python-pip -y
sudo apt install python3-pip -y
wget https://bootstrap.pypa.io/get-pip.py
sudo python2.7 get-pip.py
pip2.7 install cryptography==2.2.2
git clone https://github.com/letsencrypt/letsencrypt
		;;
n|N|Nao|nao)
		;;
*) echo  "Opcao Invalida" ;; esac
	 echo "+-------------------------------------------------+OK"

#Fazendo Backup de Certificados
echo "Fazendo Backup de Certificados..."
cp -rf /etc/letsencrypt/ /etc/letsencrypt.$(date "+%Y%m%d")
rm -rf /etc/letsencrypt/archive/*
rm -rf /etc/letsencrypt/live/*
rm -rf /etc/letsencrypt/renewal/*
	 echo "+-------------------------------------------------+OK"

#Apagando certificados
echo "Deseja apagar certificados atuais? - Sim/Nao"
read CONFIRMA
case $CONFIRMA in
s|S|Sim|sim)	 
echo "Apagando Certificados..."
cd ; cd letsencrypt
./letsencrypt-auto delete
		;;
n|N|Nao|nao)
		;;
*) echo  "Opcao Invalida" ;; esac
	 echo "+-------------------------------------------------+OK"

#Parando serviços
echo "Parando alguns serviços do Zimbra..."
$UsrZ 'zmproxyctl stop' 1&> /dev/null
$UsrZ 'zmmailboxdctl stop' 1&> /dev/null
	 echo "+-------------------------------------------------+OK"

#Gerando Certificados
echo "Gerando Certificados..."
cd ; cd letsencrypt
domains=`su zimbra -c"/opt/zimbra/bin/zmprov -l gad | sort -r"`
mail_doms="" ; webmail_doms=""
for domain in $domains ; do mail_doms="$mail_doms -d mail.$domain" ; done
for domain in $domains ; do webmail_doms="$webmail_doms -d webmail.$domain" ; done
./letsencrypt-auto certonly --standalone -d `hostname --fqdn` --expand $mail_doms $webmail_doms

#./letsencrypt-auto certonly --standalone -d `hostname --fqdn` --expand \
#-d mail.domain1.com.br -d webmail.domain1.com.br \
#-d mail.domain2.com.br -d webmail.domain2.com.br
	 echo "+-------------------------------------------------+OK"
	 
#Confirmando e-mail para registro de avisos
echo "Confirmando e-mail para registro de avisos"
echo "Digite o e-mail: "
echo -n
read EMAIL
./letsencrypt-auto update_account --email $EMAIL
	 echo "+-------------------------------------------------+OK"

#Baixando e mesclando certificados
echo "Baixando e mesclando certificados..."
wget -N https://raw.githubusercontent.com/thytetgc/LetsEncrypt/master/cert_letsencrypt -O /tmp/cert_letsencrypt 1&> /dev/null
cat /tmp/cert_letsencrypt >> /etc/letsencrypt/live/`hostname --fqdn`/chain.pem
#echo "-----BEGIN CERTIFICATE-----
#MIIDSjCCAjKgAwIBAgIQRK+wgNajJ7qJMDmGLvhAazANBgkqhkiG9w0BAQUFADA/
#MSQwIgYDVQQKExtEaWdpdGFsIFNpZ25hdHVyZSBUcnVzdCBDby4xFzAVBgNVBAMT
#DkRTVCBSb290IENBIFgzMB4XDTAwMDkzMDIxMTIxOVoXDTIxMDkzMDE0MDExNVow
#PzEkMCIGA1UEChMbRGlnaXRhbCBTaWduYXR1cmUgVHJ1c3QgQ28uMRcwFQYDVQQD
#Ew5EU1QgUm9vdCBDQSBYMzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEB
#AN+v6ZdQCINXtMxiZfaQguzH0yxrMMpb7NnDfcdAwRgUi+DoM3ZJKuM/IUmTrE4O
#rz5Iy2Xu/NMhD2XSKtkyj4zl93ewEnu1lcCJo6m67XMuegwGMoOifooUMM0RoOEq
#OLl5CjH9UL2AZd+3UWODyOKIYepLYYHsUmu5ouJLGiifSKOeDNoJjj4XLh7dIN9b
#xiqKqy69cK3FCxolkHRyxXtqqzTWMIn/5WgTe1QLyNau7Fqckh49ZLOMxt+/yUFw
#7BZy1SbsOFU5Q9D8/RhcQPGX69Wam40dutolucbY38EVAjqr2m7xPi71XAicPNaD
#aeQQmxkqtilX4+U9m5/wAl0CAwEAAaNCMEAwDwYDVR0TAQH/BAUwAwEB/zAOBgNV
#HQ8BAf8EBAMCAQYwHQYDVR0OBBYEFMSnsaR7LHH62+FLkHX/xBVghYkQMA0GCSqG
#SIb3DQEBBQUAA4IBAQCjGiybFwBcqR7uKGY3Or+Dxz9LwwmglSBd49lZRNI+DT69
#ikugdB/OEIKcdBodfpga3csTS7MgROSR6cz8faXbauX+5v3gTt23ADq1cEmv8uXr
#AvHRAosZy5Q6XkjEGB5YGV8eAlrwDPGxrancWYaLbumR9YbK+rlmM6pZW87ipxZz
#R8srzJmwN0jP41ZL9c8PDHIyh8bwRLtTcm1D9SZImlJnt1ir/md2cXjbDaJWFBM5
#JDGFoqgCWjBH4d1QB7wCCZAA62RjYJsWvIjJEubSfZGL+T0yjWW06XyxV3bqxbYo
#Ob8VZRzI9neWagqNdwvYkQsEjgfbKbYK7p2CNTUQ
#-----END CERTIFICATE-----" >> /etc/letsencrypt/live/`hostname --fqdn`/chain.pem

	echo "+-------------------------------------------------+OK"
	echo "Verifique se deu tudo certo até aqui..."
	echo 
	echo 
	echo "Aperte <ENTER> para continuar..."
	read 
	sleep 3
	echo
	echo "==================EXECUTANDO======================="
	echo 
	echo 
	
#Criando, copiando e dando permissão
echo "Criando, copiando e dando permissão..."
rm -rf /opt/zimbra/ssl/letsencrypt
mkdir -p /opt/zimbra/ssl/letsencrypt 1&> /dev/null
cp /etc/letsencrypt/live/`hostname --fqdn`/* /opt/zimbra/ssl/letsencrypt/
chown zimbra:zimbra /opt/zimbra/ssl/letsencrypt/*
         echo "+-------------------------------------------------+OK"

#Copiando os certificados para o Zimbra
echo "Copiando os certificados para o Zimbra..."
$UsrZ 'cd /opt/zimbra/ssl/letsencrypt/'
$UsrZ 'cd /opt/zimbra/ssl/letsencrypt/ ; /opt/zimbra/bin/zmcertmgr verifycrt comm /opt/zimbra/ssl/letsencrypt/privkey.pem /opt/zimbra/ssl/letsencrypt/cert.pem /opt/zimbra/ssl/letsencrypt/chain.pem'
$UsrZ 'cp -a /opt/zimbra/ssl/zimbra /opt/zimbra/ssl/zimbra.$(date "+%Y%m%d")'
$UsrZ 'rm -f /opt/zimbra/ssl/zimbra/commercial/commercial.key'
$UsrZ 'cp -a /opt/zimbra/ssl/letsencrypt/privkey.pem /opt/zimbra/ssl/zimbra/commercial/commercial.key'
$UsrZ 'cd /opt/zimbra/ssl/letsencrypt/ ; /opt/zimbra/bin/zmcertmgr deploycrt comm /opt/zimbra/ssl/letsencrypt/cert.pem /opt/zimbra/ssl/letsencrypt/chain.pem'
	 echo "+-------------------------------------------------+OK"

#Fechando porta 80
echo "Fechando Porta 80..."
iptables -D INPUT -p tcp -m tcp --dport 80 -j ACCEPT
/opt/rc.firewall 1&> /dev/null
	 echo "+-------------------------------------------------+OK"

#Inicia os serviços
echo "Inicia os serviços..."
$UsrZ 'zmproxyctl start' 1&> /dev/null
$UsrZ 'zmmailboxdctl start' 1&> /dev/null
$UsrZ 'zmtlsctl redirect' 1&> /dev/null
	 echo "+-------------------------------------------------+OK"

#Reinicia Zimbra
	echo
	echo
	echo "Aperte <ENTER> para reiniciar o Zimbra..."
	read 
	sleep 5
	echo
	echo "===================PARANDO========================"
	echo
	echo "Parando o Zimbra"
$UsrZ 'zmcontrol stop'
	echo "+-------------------------------------------------+OK"
	echo
	echo
	echo "Aperte <ENTER> para Iniciar o Zimbra..."
	read 
	sleep 5
	echo
	echo "==================INICIANDO======================="
	echo
	echo "Iniciando o Zimbra"
$UsrZ 'zmcontrol start'
	echo "+-------------------------------------------------+OK"
	echo
	echo "Status do Zimbra"
$UsrZ 'zmcontrol status'
	echo "+-------------------------------------------------+OK"
