#!/bin/bash
#+----------------GERANDO LOG-----------------------+OK"
SCRIPT=`basename $0`
LOG=`echo /Scripts_Zimbra/$SCRIPT.log | sed s/'.sh'/'.log'/g`
exec &> >(tee -a "$LOG")
echo "[`date`] ==== Inicio de rotina..."
#+----------------GERANDO LOG-----------------------+OK"

clear

#Checa se o usuario é root
LOCAL_USER=`id -u -n`

if [ $LOCAL_USER != "root" ] ; then
	echo "     Rodar como usuario root"
	echo "     saindo..."
	echo ""
	exit
fi
	dir="Diretorio Atual		 : `pwd`"
	hostname="Hostname			 : `hostname --fqdn`"
	ip="IP						 : `ifconfig | awk 'NR>=2 && NR<=2' | awk '{print $3}'`"
    versaoso="Versao S.O.		 : `lsb_release -d | cut -d : -f 2- | sed 's/^[ \t]*//;s/[ \t]*$//'`"
	release="Release			 : `lsb_release -r | cut -d : -f 2- | sed 's/^[ \t]*//;s/[ \t]*$//'`"
	codename="Codename			 : `lsb_release -c | cut -d : -f 2- | sed 's/^[ \t]*//;s/[ \t]*$//'`"
	kernel="Kernel				 : `uname -r`"
	arquitetura="Arquitetura	 : `uname -m`"
	versaozimbra="Versao Zimbra : `su - zimbra -c 'zmcontrol -v'`"
    echo "+-------------------------------------------------+"
    echo "|           Utilitario para Zimbra  v1.2          |"
    echo "+-------------------------------------------------+"
    echo "+-------------------------------------------------+"
    echo "| Escrito por:                                    |"
    echo "| Thiago Castro - www.hostlp.cloud                |"
    echo "+-------------------------------------------------+"
    echo
    echo $dir
	echo "+-------------------------------------------------+"
	echo $hostname
	echo "+-------------------------------------------------+"
	echo $ip
	echo "+-------------------------------------------------+"
	echo $versaoso
	echo "+-------------------------------------------------+"
	echo $release
	echo "+-------------------------------------------------+"
	echo $codename
	echo "+-------------------------------------------------+"
    echo $kernel
	echo "+-------------------------------------------------+"
    echo $arquitetura
	echo "+-------------------------------------------------+"
	echo $versaozimbra
	echo "+-------------------------------------------------+"
	echo
	echo "Aperte <ENTER> para continuar e começar..."
	read 
	sleep 3
	echo
	echo "==================EXECUTANDO======================="
	echo
	
zmprov="/opt/zimbra/bin/zmprov";

# Limpa tela
clear

# Lista de e-mails para importar
# user@dominio.com.br:123456:user:group
lista=/Scripts_Zimbra/lista_emails

echo "Alterar senha no primeiro Login? - Sim/Nao"
	read CONFIRMA
	case $CONFIRMA in
	s|S|Sim|sim)

while IFS=: read -r email senha nome snome
	do
$zmprov ca $email $senha givenName "$nome" sn "$snome" displayName "$nome $snome"
	echo "Senha : $senha ==> Mail : $email ==> Nome : $nome ==> Sobrenome : $snome" >> /Scripts_Zimbra/log_de_contas_importadas.txt
for each in `$zmprov -l gaa | grep $email`; do $zmprov ma $each zimbraPasswordMustChange TRUE 2>/dev/null 
	printf 'OK --> '
	echo "$email" ; done
done < "$lista"
	;;

n|N|Nao|nao)
while IFS=: read -r email senha nome snome
	do
$zmprov ca $email $senha givenName "$nome" sn "$snome" displayName "$nome $snome"
	echo "Senha : $senha ==> Mail : $email ==> Nome : $nome ==> Sobrenome : $snome" >> /Scripts_Zimbra/log_de_contas_importadas.txt
	for each in `$zmprov -l gaa | grep $email`; do $zmprov ma $each zimbraPasswordMustChange FALSE 2>/dev/null
	printf 'OK --> '
	echo "$email" ; done
done < "$lista"
	;;
*) echo  "Opcao Invalida" ;; esac

echo "[`date`] ==== Fim de rotina..."
