#!/bin/bash

clear

#Variavel
UsrZ="su - zimbra -c"

#Checa se o usuario é root
LOCAL_USER=`id -u -n`

if [ $LOCAL_USER != "root" ] ; then
        echo "     Rodar como usuario root"
        echo "     saindo..."
        echo ""
        exit
fi
Principal() {
         clear
     echo "+-------------------------------------------------+"
     echo "|           Utilitario para Zimbra     v1.5       |"
     echo "+-------------------------------------------------+"
     echo "|         Limitar contas por Dominio              |"
     echo "+-------------------------------------------------+"
     echo "| Escrito por:                                    |"
     echo "| Thiago Castro - www.hostlp.cloud                |"
     echo "+-------------------------------------------------+"
     echo
     echo
     echo "Opcoes:"
     echo "1. Listar dominios configurados"
         echo "2. Verificar limite atual de um dominio"
         echo "3. Alterar limites de um dominio"
         echo
     echo "4. Sair"
         echo
         echo
     echo -n "Entre com a opcao desejada => "
     read opcao
     echo
     case $opcao in
        1) Listar ;;
                2) Limite ;;
                3) Alterar ;;
        4) exit ;;
        *) "Opcao desconhecida." ; echo ; Principal ;;
     esac
}

#Transforma em Kb Mb Gb e Tb
function human_size {
sum=$1

hum[1024]="Kb"
hum[$((1024 * 1024))]="Mb"
hum[$((1024 * 1024 * 1024))]="Gb"
hum[$((1024 * 1024 * 1024 * 1024))]="Tb"

x=$((1024 * 1024 * 1024 * 1024))

if [ $sum -ge 1024 ]; then

while [ $x -ge 1024 ]; do

if [ $sum -ge $x ]; then
/usr/bin/printf "%.1f%s\n" "$(echo $sum / $x | bc -l | sed 's/\,/./g')" "${hum[$x]}"
break
fi

x=$(($x / 1024))
done
else
printf "%sb\n" $sum
fi
}


Listar() {
        echo "Dominios configurados no Zimbra..."
        echo
$UsrZ 'zmprov gad |sort'
        echo
    echo "Pressione qualquer tecla para continuar..."
    read msg
    Principal
}

Limite() {
        echo -n "Verificar limite atual do dominio: "
        read DOMINIO
maxaccounts=`$UsrZ 'zmprov gd '$DOMINIO' zimbraDomainMaxAccounts | cut -f2 -d " " | sed '/name/d' | sed '/^$/d''`
domainusage=`$UsrZ 'zmprov gd '$DOMINIO' | grep -w zimbraAggregateQuotaLastUsage | cut -f2 -d " "'`
domaintotal=`$UsrZ 'zmprov gd '$DOMINIO' | grep -w zimbraDomainAggregateQuota | cut -f2 -d " "'`
        echo
echo "Dominio: $DOMINIO"
echo "Contas: $maxaccounts"
echo "Espaço: $(human_size $domaintotal)"
echo "Usado: $(human_size $domainusage)"
        echo
    echo "Pressione qualquer tecla para continuar..."
    read msg
    Principal
}

Alterar() {
        echo -n "Alterar limite atual do dominio: "
        read DOMINIO
        echo "(10737418240 = 10GB / 21474836480 = 20GB / 32212254720 = 30GB / 42949672960 = 40GB / 53687091200 = 50GB)"
        echo -n "Digite em bytes a quota do novo Dominio: "
        read DOMANINQUOTA
        echo -n "Quantas contas? "
        read QTSCONTAS
$UsrZ 'zmprov md '$DOMINIO' zimbraDomainMaxAccounts '$QTSCONTAS''
$UsrZ 'zmprov md '$DOMINIO' zimbraDomainAggregateQuota '$DOMANINQUOTA''
$UsrZ 'zmprov md '$DOMINIO' zimbraAggregateQuotaLastUsage '$DOMANINQUOTA''
        echo
        echo "Alterado"
        echo
    echo "Pressione qualquer tecla para continuar..."
    read msg
    Principal
}
Principal
