#!/bin/bash
#+----------------GERANDO LOG-----------------------+OK"
SCRIPT=`basename $0`
LOG=`echo /opt/zimbra/$SCRIPT.log | sed s/'.sh'/'.log'/g`
exec &> >(tee -a "$LOG")
echo "[`date`] ==== Inicio de rotina..."
#+----------------GERANDO LOG-----------------------+OK"

clear

#Checa se o usuario é root
LOCAL_USER=`id -u -n`

if [ $LOCAL_USER != "root" ] ; then
	echo "     Rodar como usuario root"
	echo "     saindo..."
	echo ""
	exit
fi
	dir="Diretorio Atual		 : `pwd`"
	hostname="Hostname			 : `hostname --fqdn`"
	ip="IP						 : `wget -qO - icanhazip.com`"
	#ip="IP						 : `ifconfig | awk 'NR>=2 && NR<=2' | awk '{print $3}'`"
    versaoso="Versao S.O.		 : `lsb_release -d | cut -d : -f 2- | sed 's/^[ \t]*//;s/[ \t]*$//'`"
	release="Release			 : `lsb_release -r | cut -d : -f 2- | sed 's/^[ \t]*//;s/[ \t]*$//'`"
	codename="Codename			 : `lsb_release -c | cut -d : -f 2- | sed 's/^[ \t]*//;s/[ \t]*$//'`"
	kernel="Kernel				 : `uname -r`"
	arquitetura="Arquitetura	 : `uname -m`"
	versaozimbra="Versao Zimbra : `su - zimbra -c 'zmcontrol -v'`"
    echo "+-------------------------------------------------+"
    echo "|           Utilitario para Zimbra  v1.35         |"
    echo "+-------------------------------------------------+"
    echo "+-------------------------------------------------+"
    echo "| Escrito por:                                    |"
    echo "| Thiago Castro - www.hostlp.cloud                |"
    echo "+-------------------------------------------------+"
    echo
    echo $dir
	echo "+-------------------------------------------------+"
	echo $hostname
	echo "+-------------------------------------------------+"
	echo $ip
	echo "+-------------------------------------------------+"
	echo $versaoso
	echo "+-------------------------------------------------+"
	echo $release
	echo "+-------------------------------------------------+"
	echo $codename
	echo "+-------------------------------------------------+"
    echo $kernel
	echo "+-------------------------------------------------+"
    echo $arquitetura
	echo "+-------------------------------------------------+"
	echo $versaozimbra
	echo "+-------------------------------------------------+"
	echo
	echo "Aperte <ENTER> para continuar e começar..."
	read 
	sleep 5
	echo
	echo "==================EXECUTANDO======================="
	echo


#Variaveis
UsrZ="su - zimbra -c"
source /opt/zimbra/bin/zmshutil
zmsetvars
zmprov="/opt/zimbra/bin/zmprov"

Principal() {
clear
		echo
        echo "Escolha qual forma de Indexar"
        echo
		echo "1. Indexar por e-mail"
        echo "2. Indexar todos os e-mails"
		echo
        echo "3. Sair"
        echo
        echo
		echo -n "Entre com a opcao desejada => "
		read opcao
		echo
		case $opcao in
        1) IFM ;;
        2) IAM ;;
        3) exit ;;
        *) "Opcao desconhecida." ; echo ; Principal ;;
     esac
}

IFM() {
echo "Digite o e-mail a ser indexado"
echo -n "E-Mail: "
read EMAIL
echo

echo "Colocando a conta em manutenção"
$zmprov ma $EMAIL zimbraAccountStatus maintenance
	 echo "+-------------------------------------------------+OK"
	 
echo "Deletando o index atual da conta"
rm /opt/zimbra/index/0/$($zmprov gmi $EMAIL | grep mailboxId | awk '{ print $2 }')/index/* -Rf
	 echo "+-------------------------------------------------+OK"

echo "Indexando"
$zmprov rim $EMAIL start >/dev/null

while [ `$zmprov rim $EMAIL status|wc -l` != 1 ]

do

echo -n . && sleep 2
done
echo .
	 echo "+-------------------------------------------------+OK"

echo "Reativando a conta..."
$zmprov ma $EMAIL zimbraAccountStatus active
	 echo "+-------------------------------------------------+OK"

echo
echo "Deseja Reiniciar o Zimbra? - Sim/Nao"
read CONFIRMA
case $CONFIRMA in
s|S|Sim|sim)
echo "Reiniciando o zimbra..."
$UsrZ 'zmcontrol restart'
               ;;
n|N|Nao|nao)
                ;;
*) echo  "Opcao Invalida" ;; esac

}
Principal

IAM() {
echo "Listando todas as contas"
for EMAIL in $($zmprov -l gaa)
do
	 echo "+-------------------------------------------------+OK"
echo $EMAIL
echo

echo "Colocando a conta em manutenção"
$zmprov ma $EMAIL zimbraAccountStatus maintenance
	 echo "+-------------------------------------------------+OK"
	 
echo "Deletando o index atual da conta"
rm /opt/zimbra/index/0/$($zmprov gmi $EMAIL | grep mailboxId | awk '{ print $2 }')/index/* -Rf
	 echo "+-------------------------------------------------+OK"

echo "Indexando"
$zmprov rim $EMAIL start >/dev/null

while [ `$zmprov rim $EMAIL status|wc -l` != 1 ]

do

echo -n . && sleep 2
done
echo .
	 echo "+-------------------------------------------------+OK"

echo "Reativando a conta..."
$zmprov ma $EMAIL zimbraAccountStatus active
done
	 echo "+-------------------------------------------------+OK"

echo
echo "Deseja Reiniciar o Zimbra? - Sim/Nao"
read CONFIRMA
case $CONFIRMA in
s|S|Sim|sim)
echo "Reiniciando o zimbra..."
$UsrZ 'zmcontrol restart'
               ;;
n|N|Nao|nao)
                ;;
*) echo  "Opcao Invalida" ;; esac

}
Principal

echo "[`date`] ==== Fim de rotina..."
