#!/bin/bash
#+----------------GERANDO LOG-----------------------+OK"
SCRIPT=`basename $0`
LOG=`echo /opt/zimbra/$SCRIPT.log | sed s/'.sh'/'.log'/g`
exec &> >(tee -a "$LOG")
echo "[`date`] ==== Inicio de rotina..."
#+----------------GERANDO LOG-----------------------+OK"

clear

#Checa se o usuario é root
LOCAL_USER=`id -u -n`

if [ $LOCAL_USER != "root" ] ; then
	echo "     Rodar como usuario root"
	echo "     saindo..."
	echo ""
	exit
fi
	dir="Diretorio Atual		 : `pwd`"
	hostname="Hostname			 : `hostname --fqdn`"
	ip="IP						 : `wget -qO - icanhazip.com`"
	#ip="IP						 : `ifconfig | awk 'NR>=2 && NR<=2' | awk '{print $3}'`"
    versaoso="Versao S.O.		 : `lsb_release -d | cut -d : -f 2- | sed 's/^[ \t]*//;s/[ \t]*$//'`"
	release="Release			 : `lsb_release -r | cut -d : -f 2- | sed 's/^[ \t]*//;s/[ \t]*$//'`"
	codename="Codename			 : `lsb_release -c | cut -d : -f 2- | sed 's/^[ \t]*//;s/[ \t]*$//'`"
	kernel="Kernel				 : `uname -r`"
	arquitetura="Arquitetura	 : `uname -m`"
	versaozimbra="Versao Zimbra : `su - zimbra -c 'zmcontrol -v'`"
    echo "+-------------------------------------------------+"
    echo "|           Utilitario para Zimbra  v1.35         |"
    echo "+-------------------------------------------------+"
    echo "+-------------------------------------------------+"
    echo "| Escrito por:                                    |"
    echo "| Thiago Castro - www.hostlp.cloud                |"
    echo "+-------------------------------------------------+"
    echo
    echo $dir
	echo "+-------------------------------------------------+"
	echo $hostname
	echo "+-------------------------------------------------+"
	echo $ip
	echo "+-------------------------------------------------+"
	echo $versaoso
	echo "+-------------------------------------------------+"
	echo $release
	echo "+-------------------------------------------------+"
	echo $codename
	echo "+-------------------------------------------------+"
    echo $kernel
	echo "+-------------------------------------------------+"
    echo $arquitetura
	echo "+-------------------------------------------------+"
	echo $versaozimbra
	echo "+-------------------------------------------------+"
	echo
	echo "Aperte <ENTER> para continuar e começar..."
	read 
	sleep 5
	echo
	echo "==================EXECUTANDO======================="
	echo


#Variaveis
UsrZ="su - zimbra -c"
source /opt/zimbra/bin/zmshutil
zmsetvars
zmprov="/opt/zimbra/bin/zmprov"

Principal() {
clear
		echo
        echo "Escolha qual forma de Indexar"
        echo
		echo "1. Indexar por e-mail"
        echo "2. Indexar todos os e-mails"
		echo
        echo "3. Sair"
        echo
        echo
		echo -n "Entre com a opcao desejada => "
		read opcao
		echo
		case $opcao in
        1) IFM ;;
        2) IAM ;;
        3) exit ;;
        *) "Opcao desconhecida." ; echo ; Principal ;;
     esac
}

IFM() {
echo "Digite o e-mail a ser indexado"
echo -n "E-Mail: "
read EMAIL
echo

echo "Colocando a conta em manutenção"
$zmprov ma $EMAIL zimbraAccountStatus maintenance
	 echo "+-------------------------------------------------+OK"
	 
echo "Deletando o index atual da conta"
rm /opt/zimbra/index/0/$($zmprov gmi $EMAIL | grep mailboxId | awk '{ print $2 }')/index/* -Rf
	 echo "+-------------------------------------------------+OK"

echo "Reiniciando MailBoxD"
$UsrZ 'zmmailboxdctl restart'
	 echo "+-------------------------------------------------+OK"

echo "Indexando"
$zmprov rim $EMAIL start >/dev/null

while [ `$zmprov rim $EMAIL status|wc -l` != 1 ]

do

echo -n . && sleep 2
done
echo .
	 echo "+-------------------------------------------------+OK"

#echo "Status da Indexação"
#$zmprov rim $EMAIL status | tail -n 1
#	 echo "+-------------------------------------------------+OK"

echo "Reativando a conta..."
$zmprov ma $EMAIL zimbraAccountStatus active
	 echo "+-------------------------------------------------+OK"

echo
echo "Deseja Reiniciar o Zimbra? - Sim/Nao"
read CONFIRMA
case $CONFIRMA in
s|S|Sim|sim)
echo "Reiniciando o zimbra..."
$UsrZ 'zmcontrol restart'
               ;;
n|N|Nao|nao)
                ;;
*) echo  "Opcao Invalida" ;; esac

	Principal
}

IAM() {
# Gerando lista de contas bloqueadas
mv -f /opt/locked_accounts /opt/locked_accounts_$(date "+%d%m%Y%H%M%S")
$zmprov -l sa "(zimbraAccountStatus=locked)" > /opt/locked_accounts
$zmprov -l sa "(zimbraAccountStatus=lockout)" >> /opt/locked_accounts
$zmprov -l sa "(zimbraAccountStatus=closed)" >> /opt/locked_accounts

# Gerando lista de todas as contas
$zmprov -l gaa | sort | egrep -v "^admin" > /opt/all_accounts

echo "Colocando todas as contas em manutenção"
echo
>/tmp/accounts_maintenance ; for EMAIL in `cat /opt/all_accounts`; do
echo $EMAIL
echo "ma $EMAIL zimbraAccountStatus maintenance" >> /tmp/accounts_maintenance; done
cat /tmp/accounts_maintenance | /opt/zimbra/bin/zmprov >/dev/null
	echo "+-------------------------------------------------+OK"
 
echo
echo "Deletando o index de todas as contas"
echo
for EMAIL in `cat /opt/all_accounts`; do
#>/tmp/accounts_index ; for EMAIL in $($zmprov -l gaa | sort | egrep -v "^admin"); do
echo $EMAIL
#echo "/opt/zimbra/index/0/$($zmprov gmi $EMAIL | grep mailboxId | awk '{ print $2 }')/index/* -Rf" >> /tmp/accounts_index; done
#cat /tmp/accounts_index | rm >/dev/null
rm /opt/zimbra/index/0/$($zmprov gmi $EMAIL | grep mailboxId | awk '{ print $2 }')/index/* -Rf; done
	 echo "+-------------------------------------------------+OK"

echo "Reiniciando MailBoxD"
echo
$UsrZ 'zmmailboxdctl restart'
	 echo "+-------------------------------------------------+OK"

echo "Indexando"
echo
for EMAIL in `cat /opt/all_accounts`; do
echo $EMAIL
$zmprov rim $EMAIL start >/dev/null

while [ `$zmprov rim $EMAIL status|wc -l` != 1 ]

do

echo -n . && sleep 2
done
echo .
done
	 echo "+-------------------------------------------------+OK"

#echo "Status da Indexação"
#$zmprov rim $EMAIL status | tail -n 1
#	 echo "+-------------------------------------------------+OK"

echo
echo "Reativando a conta..."
echo
>/tmp/accounts_maintenance ; for EMAIL in `cat /opt/all_accounts`; do
echo $EMAIL
echo "ma $EMAIL zimbraAccountStatus active" >> /tmp/accounts_maintenance; done
cat /tmp/accounts_maintenance | /opt/zimbra/bin/zmprov >/dev/null
	 echo "+-------------------------------------------------+OK"

# Voltando as contas bloqueadas
for USER in `cat /opt/locked_accounts`; do /opt/zimbra/bin/zmprov ma $USER zimbraAccountStatus locked; done

echo
echo "Deseja Reiniciar o Zimbra? - Sim/Nao"
read CONFIRMA
case $CONFIRMA in
s|S|Sim|sim)
echo "Reiniciando o zimbra..."
$UsrZ 'zmcontrol restart'
               ;;
n|N|Nao|nao)
                ;;
*) echo  "Opcao Invalida" ;; esac

	Principal
}
Principal

echo "[`date`] ==== Fim de rotina..."
