#!/bin/bash

#+----------------GERANDO LOG-----------------------+OK"
SCRIPT=`basename $0`
LOG=`echo /Scripts_Zimbra/$SCRIPT.log | sed s/'.sh'/'.log'/g`
exec &> >(tee -a "$LOG")
echo "[`date`] ==== Inicio de rotina..."
#+----------------GERANDO LOG-----------------------+OK"

cd /tmp/
clear

#Checa se o usuario é root
LOCAL_USER=`id -u -n`

if [ $LOCAL_USER != "root" ] ; then
        echo "     Rodar como usuario root"
        echo "     saindo..."
        echo ""
        exit
fi

        clear
        dir="Diretorio Atual             : `pwd`"
        hostname="Hostname               : `hostname --fqdn`"
        ip="IP                           : `ifconfig | awk 'NR>=2 && NR<=2' | awk '{print $3}'`"
        versaoso="Versao S.O.            : `lsb_release -d | cut -d : -f 2- | sed 's/^[ \t]*//;s/[ \t]*$//'`"
        release="Release                 : `lsb_release -r | cut -d : -f 2- | sed 's/^[ \t]*//;s/[ \t]*$//'`"
        codename="Codename               : `lsb_release -c | cut -d : -f 2- | sed 's/^[ \t]*//;s/[ \t]*$//'`"
        kernel="Kernel                   : `uname -r`"
        arquitetura="Arquitetura         : `uname -m`"
        versaozimbra="Versao Zimbra      : `/opt/zimbra/bin/zmcontrol -v`"
     echo
     echo "+-------------------------------------------------+"
     echo "|           Utilitario para Zimbra                |"
     echo "+-------------------------------------------------+"
     echo "|      Relatório de Contas do Zimbra    v15.      |"
     echo "+-------------------------------------------------+"
     echo "| Escrito por:                                    |"
     echo "| Thiago Castro - www.hostlp.net                  |"
     echo "+-------------------------------------------------+"
     echo
     echo $dir
     echo "+-------------------------------------------------+"
     echo $hostname
     echo "+-------------------------------------------------+"
     echo $ip
     echo "+-------------------------------------------------+"
     echo $versaoso
     echo "+-------------------------------------------------+"
     echo $release
     echo "+-------------------------------------------------+"
     echo $codename
     echo "+-------------------------------------------------+"
     echo $kernel
     echo "+-------------------------------------------------+"
     echo $arquitetura
     echo "+-------------------------------------------------+"
     echo $versaozimbra
     echo "+-------------------------------------------------+"
     echo
     sleep 5
     echo
     echo "==================EXECUTANDO======================="
     echo

#Variavel
UsrZ="su - zimbra -c"

#Transforma em Kb Mb Gb e Tb
function human_size {
sum=$1

hum[1024]="Kb"
hum[$((1024 * 1024))]="Mb"
hum[$((1024 * 1024 * 1024))]="Gb"
hum[$((1024 * 1024 * 1024 * 1024))]="Tb"

x=$((1024 * 1024 * 1024 * 1024))

if [ $sum -ge 1024 ]; then

while [ $x -ge 1024 ]; do

if [ $sum -ge $x ]; then
/usr/bin/printf "%.1f%s\n" "$(echo $sum / $x | bc -l | sed 's/\,/./g')" "${hum[$x]}"
break
fi

x=$(($x / 1024))
done
else
printf "%sb\n" $sum
fi
}

#Gera os relatórios para cada dominio
output="/tmp/accountusage"
outputd="/tmp/domainusage"
domain=$1
sendto="thiago@hostlp.net"
rm -f $output
touch $output
rm -f $outputd
touch $outputd

#Variaveis
server=`/opt/zimbra/bin/zmhostname`
/opt/zimbra/bin/zmprov gqu $server|grep $domain|awk {'print $1" "$3" "$2'}|sort|while read line
do
user=`echo $line|cut -f1 -d " "`
usage=`echo $line|cut -f2 -d " "`
quota=`echo $line|cut -f3 -d " "`
status=`/opt/zimbra/bin/zmprov ga $user | grep  ^zimbraAccountStatus | cut -f2 -d " "`
lastlogind=`su - zimbra -c '/opt/zimbra/bin/zmaccts | grep '$user' '|tr -s '  ' | cut -f5 -d " "'' | cut -c1-8 | sed 's:\(....\)\(..\)\(.*\):\1/\2/\3:'`
lastloginh=`su - zimbra -c '/opt/zimbra/bin/zmaccts | grep '$user' '|tr -s '  ' | cut -f5 -d " "'' | cut -c9-14 | sed 's:\(..\)\(..\)\(.*\):\1-\2-\3:' | sed 's/-/:/g'`
imap=`/opt/zimbra/bin/zmprov ga $user | grep zimbraImapEnabled | cut -f2 -d " " | sed 's/TRUE/Ativado/g' | sed 's/FALSE/Desativado/g'`

#Gera relatorio de uso do usuario
echo "$user |Usado: $(human_size $usage) - Quota: $(human_size $quota)| |Status - $status| |Imap - $imap| |Ultimo Login: $lastlogind - $lastloginh" >> $output

#Apaga o relatório se estiver vazio
find $output -type f -empty | xargs -n1 rm -f 1&> /dev/null
done

#Gera relatorio de uso do dominio
domaintotal=`/opt/zimbra/bin/zmprov gd $domain | grep -w zimbraAggregateQuotaLastUsage | cut -f2 -d " "`
domainusage=`/opt/zimbra/bin/zmprov gd $domain | grep -w zimbraDomainAggregateQuota | cut -f2 -d " "`
echo "" > $outputd
echo "Dominio: $domain - TOTAL: $(human_size $domaintotal) | USADO: $(human_size $domainusage)" >> $outputd

#Apaga o relatório se estiver vazio
#find $outputd -type f -empty | xargs -n1 rm -f 1&> /dev/null
cat $outputd >> $output

#Envia e-mail com o relatório, somente se houver o arquivo com as informações
TEM_INFO=''
cat /tmp/accountusage > /tmp/accountusage.tmp
if egrep -q "$TEM_INFO" /tmp/accountusage.tmp
then

#Tem o arquivo com informações, então envia por e-mail
cat $output | mail $sendto -s "Relatório de contas - $domain"
fi

echo "[`date`] ==== Fim de rotina..."
