#!/bin/bash
#+----------------GERANDO LOG-----------------------+OK"
SCRIPT=`basename $0`
LOG=`echo /opt/zimbra/$SCRIPT.log | sed s/'.sh'/'.log'/g`
exec &> >(tee -a "$LOG")
echo "[`date`] ==== Inicio de rotina..."
#+----------------GERANDO LOG-----------------------+OK"

clear

#Checa se o usuario é zimbra
LOCAL_USER=`id -u -n`

if [ $LOCAL_USER != "zimbra" ] ; then
	echo "     Rodar como usuario zimbra"
	echo "     saindo..."
	echo ""
	exit
fi
	dir="Diretorio Atual		 : `pwd`"
	hostname="Hostname			 : `hostname --fqdn`"
	ip="IP						 : `wget -qO - icanhazip.com`"
	#ip="IP						 : `ifconfig | awk 'NR>=2 && NR<=2' | awk '{print $3}'`"
    versaoso="Versao S.O.		 : `lsb_release -d | cut -d : -f 2- | sed 's/^[ \t]*//;s/[ \t]*$//'`"
	release="Release			 : `lsb_release -r | cut -d : -f 2- | sed 's/^[ \t]*//;s/[ \t]*$//'`"
	codename="Codename			 : `lsb_release -c | cut -d : -f 2- | sed 's/^[ \t]*//;s/[ \t]*$//'`"
	kernel="Kernel				 : `uname -r`"
	arquitetura="Arquitetura	 : `uname -m`"
	versaozimbra="Versao Zimbra : `zmcontrol -v`"
    echo "+-------------------------------------------------+"
    echo "|           Utilitario para Zimbra  v1.37         |"
    echo "+-------------------------------------------------+"
    echo "+-------------------------------------------------+"
    echo "| Escrito por:                                    |"
    echo "| Thiago Castro - www.hostlp.cloud                |"
    echo "+-------------------------------------------------+"
    echo
    echo $dir
	echo "+-------------------------------------------------+"
	echo $hostname
	echo "+-------------------------------------------------+"
	echo $ip
	echo "+-------------------------------------------------+"
	echo $versaoso
	echo "+-------------------------------------------------+"
	echo $release
	echo "+-------------------------------------------------+"
	echo $codename
	echo "+-------------------------------------------------+"
    echo $kernel
	echo "+-------------------------------------------------+"
    echo $arquitetura
	echo "+-------------------------------------------------+"
	echo $versaozimbra
	echo "+-------------------------------------------------+"
	echo
	echo "Aperte <ENTER> para continuar e começar..."
	read 
	sleep 5
	echo
	echo "==================EXECUTANDO======================="
	echo


#Variaveis
#UsrZ="su - zimbra -c"
source /opt/zimbra/bin/zmshutil
zmsetvars
zmprov="/opt/zimbra/bin/zmprov"
zmmailbox="/opt/zimbra/bin/zmmailbox"

Principal() {
clear
		echo
        echo "Escolha qual forma Mover as mensagens"
        echo
		echo "1. Por E-Mail"
        echo "2. Por Dominio"
		echo "3. TUDO"
		echo
        echo "4. Sair"
        echo
        echo
		echo -n "Entre com a opcao desejada => "
		read opcao
		echo
		case $opcao in
        1) PE ;;
        2) PD ;;
		3) ALL ;;
        4) exit ;;
        *) "Opcao desconhecida." ; echo ; Principal ;;
     esac
}

PE() {
echo "Digite o E-Mail"
echo -n "E-Mail: "
read email
echo

echo "Pegando ID das mensagens - $email"
	 echo "+-------------------------------------------------+OK"
	 echo
	 
for msgid in `zmmailbox -z -m "$email" s -l 999 -t message "in:Junk" | sort | grep mess | awk '{print $2}'`; do
	 echo "+-------------------------------------------------+OK"
	 
echo "Movendo da pasta Spam para Caixa de Entrada - MsgID: $msgid"
zmmailbox -z -m "$email" mm $msgid Inbox;

done
	 echo "+-------------------------------------------------+OK"

	 echo
	 echo "Finalizado aperte <ENTER>"
	 read
	Principal
}

PD() {
echo "Digite o Dominio"
echo -n "Dominio: "
read domain
echo

echo "Pegando contas de e-mail"
	 echo "+-------------------------------------------------+OK"
	 echo
	 
for email in `zmprov -l gaa | sort | egrep -v "^virus|^ham|^spam|^galsync" | grep $domain`; do
	 echo "+-------------------------------------------------+OK"

echo "Pegando ID das mensagens - $email"
for msgid in `zmmailbox -z -m "$email" s -l 999 -t message "in:Junk" |sort | grep mess | awk '{print $2}'`; do
	 
echo "Movendo da pasta Spam para Caixa de Entrada - MsgID: $msgid"
zmmailbox -z -m "$email" mm $msgid Inbox;

	done
done
	 echo "+-------------------------------------------------+OK"

	 echo
	 echo "Finalizado aperte <ENTER>"
	 read
	Principal
}

ALL() {
echo "Pegando todas as contas de e-mail"
	 echo "+-------------------------------------------------+OK"
	 echo

for domain in `zmprov -l gaa | sort`; do	 
for email in `zmprov -l gaa | sort | egrep -v "^virus|^ham|^spam|^galsync" | grep $domain`; do
	 echo "+-------------------------------------------------+OK"

echo "Pegando ID das mensagens - $email"
for msgid in `zmmailbox -z -m "$email" s -l 999 -t message "in:Junk" |sort | grep mess | awk '{print $2}'`; do
	 
echo "Movendo da pasta Spam para Caixa de Entrada - MsgID: $msgid"
zmmailbox -z -m "$email" mm $msgid Inbox;

		done
	done
done
	 echo "+-------------------------------------------------+OK"

	 echo
	 echo "Finalizado aperte <ENTER>"
	 read
	Principal
}
Principal

echo "[`date`] ==== Fim de rotina..."
