#!/bin/bash

##############################
#DADOS DO SERVIDOR E USUARIO##
##############################

SERVIDOR_ORIGEM='IP_ORIGEM'
#ADMIN_ORIGEM='admin@DOMAIN.com.br'
#PASSWORDADMIN_ORIGEM='SENHA_ADMIN'
USUARIO_ORIGEM='E-MAIL_ORIGEM'
PASSWORD_ORIGEM='SENHA_ORIGEM'

SERVIDOR_DESTINO='IP_DESTINO'
#ADMIN_DESTINO='admin@DOMAIN.com.br'
#PASSWORDADMIN_DESTINO='SENHA_ADMIN'
USUARIO_DESTINO='E-MAIL_DESTINO'
PASSWORD_DESTINO='SENHA_DESTINO'

########################################
##MIGRAR USUARIO POR USUARIO COM SENHA##
########################################

#imapsync --nosyncacls --subscribe --syncinternaldates --host1 $SERVIDOR_ORIGEM --user1 $USUARIO_ORIGEM --password1 $PASSWORD_ORIGEM --host2 $SERVIDOR_DESTINO --user2 $USUARIO_DESTINO --password2 $PASSWORD_DESTINO --noauthmd5

# GMAIL
imapsync --addheader --host1 $SERVIDOR_ORIGEM --ssl1 --user1 "$USUARIO_ORIGEM" --password1 "$PASSWORD_ORIGEM" --host2 $SERVIDOR_DESTINO --ssl2 --user2 "$USUARIO_DESTINO" --password2 "$PASSWORD_DESTINO" --noauthmd5 --maxbytespersecond 10000 --automap --exclude "\[Gmail\]$"
#Desativar segurança para GMAIL
#https://www.google.com/settings/security/lesssecureapps?pli=1

########################################
##MIGRAR USUARIO POR USUARIO SEM SENHA##
########################################

#imapsync --nosyncacls --subscribe --syncinternaldates --host1 $SERVIDOR_ORIGEM --user1 $USUARIO_ORIGEM --authuser1 $ADMIN_ORIGEM --password1 $PASSWORDADMIN_ORIGEM --authmech1 PLAIN --host2 $SERVIDOR_DESTINO --user2 $USUARIO_DESTINO --authuser2 $ADMIN_DESTINO --password2 $PASSWORDADMIN_DESTINO --authmech2 PLAIN --noauthmd5

######################################
##MIGRAR TODOS OS USUARIOS SEM SENHA##
######################################

#ZMPROV="/opt/zimbra/bin/zmprov"
#for USER in $($ZMPROV -l gaa); do

#imapsync --nosyncacls --subscribe --syncinternaldates --host1 $SERVIDOR_ORIGEM --user1 $USER --authuser1 $ADMIN_ORIGEM --password1 $PASSWORDADMIN_ORIGEM --authmech1 PLAIN --host2 $SERVIDOR_DESTINO --user2 $USER --authuser2 $ADMIN_DESTINO --password2 $PASSWORDADMIN_DESTINO --authmech2 PLAIN --noauthmd5

#done

######################################

